# 📱 Electronic Products Prices Dataset
The Electronic Products Prices dataset, sourced from **Datafiniti**, provides a detailed snapshot of the consumer electronics market.
It captures pricing dynamics across major US retailers like Amazon, Best Buy, and Walmart.
By tracking over 7,000 unique products, this dataset offers a granular view of how brands, merchants, and seasonal discounts (Sale vs. Regular) influence the final price.

**Objective:** Uncover pricing strategies, merchant competitiveness, and market trends in the tech industry — and build a model to **predict the average price** of a product.

---

## 📋 Dataset Column Description

| # | Column | Description |
|---|--------|-------------|
| 1 | **id** | Unique identifier for the product record. |
| 2 | **prices.amountMax** | The highest price recorded for the product. |
| 3 | **prices.amountMin** | The lowest price recorded for the product. |
| 4 | **prices.availability** | Stock status (In Stock, Out of Stock, Special Order…). |
| 5 | **prices.condition** | Physical state of the item (New, Used, Refurbished). |
| 6 | **prices.currency** | Currency of the transaction (USD, CAD…). |
| 7 | **prices.dateSeen** | Timestamp when the price was crawled from the merchant. |
| 8 | **prices.isSale** | Indicates a promotional discount (True/False). |
| 9 | **prices.merchant** | Retailer name (Amazon, Best Buy, Walmart…). |
| 10 | **prices.shipping** | Shipping cost details or 'Free Shipping'. |
| 11 | **prices.sourceURLs** | URL where the price was extracted. |
| 12 | **asins** | Amazon Standard Identification Numbers. |
| 13 | **brand** | Brand or manufacturer name (Samsung, Sony, Bose…). |
| 14 | **categories** | Granular product categories separated by commas. |
| 15 | **dateAdded** | Date when the product was first added to the dataset. |
| 16 | **dateUpdated** | Last time the product metadata was modified. |
| 17 | **ean / upc** | Standardized product bar codes. |
| 18 | **imageURLs** | Links to the product's marketing images. |
| 19 | **keys** | Internal unique keys generated by combining brand and model. |
| 20 | **manufacturer** | Company that manufactured the electronics. |
| 21 | **manufacturerNumber** | Manufacturer Part Number (MPN). |
| 22 | **name** | Full commercial title of the product. |
| 23 | **primaryCategories** | Broad category mapping (Electronics, Software…). |
| 24 | **sourceURLs** | General URLs for the product across platforms. |
| 25 | **weight** | Shipping weight of the product (includes units). |

---

# 📦 Importing Libraries

In [1]:
import pandas as pd                                                                               # Import pandas for data manipulation and analysis
import numpy as np                                                                                # Import numpy for numerical operations
import plotly.express as px                                                                       # Import plotly.express for data visualization
import streamlit as st                                                                            # Import streamlit for building web applications
import re                                                                                         # Import re for working with regular expressions (text cleaning)
from sklearn.preprocessing import LabelEncoder, StandardScaler , OneHotEncoder , OrdinalEncoder   # Import LabelEncoder to convert categorical data into numeric form
                                                                                                  # Import StandardScaler to scale numerical features
from sklearn.ensemble import RandomForestClassifier                                               # Import RandomForestClassifier for building a classification model
from sklearn.model_selection import train_test_split                                              # Import train_test_split to split data into training and testing sets
from sklearn.metrics import accuracy_score, classification_report                                 # Import accuracy_score and classification_report for evaluating the model's performance

# 📂 Reading the Dataset

In [2]:
df = pd.read_csv('DatafinitiElectronicsProductsPricingData.csv', encoding='latin-1')
pd.options.display.max_columns = None                                         # Set pandas option to display all columns in the DataFrame
pd.options.display.max_rows = None                                            # Set pandas option to display all rows in the DataFrame
df.head()

,id,prices.amountMax,prices.amountMin,prices.availability,prices.condition,prices.currency,prices.dateSeen,prices.isSale,prices.merchant,prices.shipping,prices.sourceURLs,asins,brand,categories,dateAdded,dateUpdated,ean,imageURLs,keys,manufacturer,manufacturerNumber,name,primaryCategories,sourceURLs,upc,weight,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,AVphzgbJLJeJML43fA0o,104.99,104.99,Yes,New,USD,"2017-03-30T06:00:00Z,2017-03-10T22:00:00Z,2017...",False,Bestbuy.com,NaN,http://www.bestbuy.com/site/sanus-tv-wall-moun...,B00C78VIUE,Sanus,"Audio & Video Accessories,TV Mounts,TV Accesso...",2015-04-13T12:00:51Z,2018-05-12T18:59:48Z,NaN,https://images-na.ssl-images-amazon.com/images...,sanusvlf410b110inchsuperslimfullmotionmountfor...,NaN,VLF410B1,Sanus VLF410B1 10-Inch Super Slim Full-Motion ...,Electronics,https://www.amazon.com/Sanus-VLF410B1-10-Inch-...,7.93796E+11,32.8 pounds,NaN,NaN,NaN,NaN,NaN
1,AVpgMuGwLJeJML43KY_c,69.00,64.99,In Stock,New,USD,2017-12-14T06:00:00Z,True,Walmart.com,Expedited,https://www.walmart.com/ip/BOYTONE-BT210FB-BLA...,"B018K251JE,B00VILQKQ8",Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",2015-05-18T14:14:56Z,2018-06-13T19:39:02Z,NaN,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN
2,AVpgMuGwLJeJML43KY_c,69.00,69.00,In Stock,New,USD,2017-09-08T05:00:00Z,False,Walmart.com,Expedited,https://www.walmart.com/ip/Boytone-BT-210F-Blu...,"B018K251JE,B00VILQKQ8",Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",2015-05-18T14:14:56Z,2018-06-13T19:39:02Z,NaN,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN
3,AVpgMuGwLJeJML43KY_c,69.99,69.99,Yes,New,USD,2017-10-10T05:00:00Z,False,Bestbuy.com,NaN,https://www.bestbuy.com/site/boytone-2500w-2-1...,"B018K251JE,B00VILQKQ8",Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",2015-05-18T14:14:56Z,2018-06-13T19:39:02Z,NaN,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN
4,AVpgMuGwLJeJML43KY_c,66.99,66.99,Yes,New,USD,2017-08-28T07:00:00Z,False,Bestbuy.com,NaN,https://www.bestbuy.com/site/boytone-2500w-2-1...,"B018K251JE,B00VILQKQ8",Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",2015-05-18T14:14:56Z,2018-06-13T19:39:02Z,NaN,https://images-na.ssl-images-amazon.com/images...,boytone2500w21chhometheatersystemblackdiamond/...,Boytone,BT-210F,Boytone - 2500W 2.1-Ch. Home Theater System - ...,Electronics,http://reviews.bestbuy.com/3545/4784804/review...,6.42015E+11,14 pounds,NaN,NaN,NaN,NaN,NaN

# 🔍 Dataset Overview

In [3]:
import kagglehub

path = kagglehub.dataset_download("datafiniti/electronic-products-prices")

print("Path to dataset files:", path)

import os

df = pd.read_csv(os.path.join(path, 'DatafinitiElectronicsProductsPricingData.csv'), encoding='latin-1')
pd.options.display.max_columns = None                                         # Set pandas option to display all columns in the DataFrame
pd.options.display.max_rows = None                                            # Set pandas option to display all rows in the DataFrame
df.head()

ModuleNotFoundError: No module named 'kagglehub'

In [ ]:
df.describe()

       prices.amountMax  prices.amountMin   Unnamed: 28
count      14592.000000      14592.000000  6.000000e+00
mean         509.578897        487.323215  8.849380e+11
std         1008.512738        967.083200  0.000000e+00
min            1.000000          1.000000  8.849380e+11
25%           79.990000         79.950000  8.849380e+11
50%          195.000000        188.035000  8.849380e+11
75%          499.990000        499.000000  8.849380e+11
max        26871.000000      26871.000000  8.849380e+11

In [ ]:
df.describe(include='object')

,id,prices.availability,prices.condition,prices.currency,prices.dateSeen,prices.merchant,prices.shipping,prices.sourceURLs,asins,brand,categories,dateAdded,dateUpdated,ean,imageURLs,keys,manufacturer,manufacturerNumber,name,primaryCategories,sourceURLs,upc,weight,Unnamed: 26,Unnamed: 27,Unnamed: 29,Unnamed: 30
count,14592,12667,13189,14592,14592,13820,8793,14592,14592,14592,14592,14592,14592,4208,14592,14592,7618,14592,14592,14592,14592,14592,14592,39,18,12,6
unique,1245,17,18,5,6984,1558,212,8529,1245,309,1199,1176,1045,211,1242,1245,267,1245,1229,6,1192,654,805,2,2,1,1
top,AV1YCe4G-jtxr-f31MVO,In Stock,New,USD,2018-05-26T15:00:00Z,Bestbuy.com,Free Expedited Shipping for most orders over $49,https://www.amazon.com/Escort-Range-Radar-Lase...,"B00FPWOU4U,B01EIUOSRS,B00Q3YZMAA",Sony,"Computers,See more Genuine Apple 45w MagSafe 2...",2017-03-06T14:57:09Z,2018-06-20T13:17:06Z,8.87276E+11,There are too many imageURLs objects to show. ...,applemacbookair133corei58gbram128gbflashstorag...,Sony,A1466,Details About Apple Macbook Air 13.3 Laptop (e...,Electronics,There are too many sourceURLs objects to show....,8.87276E+11,1 pounds,19048215475,8.88863E+11,6.3 pounds,4.8 pounds
freq,106,5597,10833,14496,191,4453,2636,27,106,1618,106,136,106,327,370,106,723,106,106,14482,1534,1140,226,27,12,12,6

In [ ]:
# Checking the number of unique values in each column
for col in df:
    print(col, ':', df[col].nunique())
    print('-'*25)

id : 1245
-------------------------
prices.amountMax : 4697
-------------------------
prices.amountMin : 4907
-------------------------
prices.availability : 17
-------------------------
prices.condition : 18
-------------------------
prices.currency : 5
-------------------------
prices.dateSeen : 6984
-------------------------
prices.isSale : 2
-------------------------
prices.merchant : 1558
-------------------------
prices.shipping : 212
-------------------------
prices.sourceURLs : 8529
-------------------------
asins : 1245
-------------------------
brand : 309
-------------------------
categories : 1199
-------------------------
dateAdded : 1176
-------------------------
dateUpdated : 1045
-------------------------
ean : 211
-------------------------
imageURLs : 1242
-------------------------
keys : 1245
-------------------------
manufacturer : 267
-------------------------
manufacturerNumber : 1245
-------------------------
name : 1229
-------------------------
primaryCategories : 6
-------------------------
sourceURLs : 1192
-------------------------
upc : 654
-------------------------
weight : 805
-------------------------
Unnamed: 26 : 2
-------------------------
Unnamed: 27 : 2
-------------------------
Unnamed: 28 : 1
-------------------------
Unnamed: 29 : 1
-------------------------
Unnamed: 30 : 1
-------------------------

# 🧹 Data Preprocessing

## Step 1 — Drop Unnecessary / Mostly-Empty Columns

In [ ]:
df.drop(['id','Unnamed: 26','Unnamed: 27','Unnamed: 28','Unnamed: 29','Unnamed: 30',
         'imageURLs','prices.sourceURLs','manufacturer','asins','name',
         'upc','keys','ean','manufacturerNumber'], axis=1, inplace=True)

# Make all column names lowercase and remove dots for easier access
df.columns = df.columns.str.lower().str.replace('.', '', regex=False)
print(f"Remaining columns ({len(df.columns)}):")
df.columns

Remaining columns (16):

Index(['pricesamountmax', 'pricesamountmin', 'pricesavailability',
       'pricescondition', 'pricescurrency', 'pricesdateseen', 'pricesissale',
       'pricesmerchant', 'pricesshipping', 'brand', 'categories', 'dateadded',
       'dateupdated', 'primarycategories', 'sourceurls', 'weight'],
      dtype='object')

## Step 2 — Missing Values

In [ ]:
# Missing value percentage
(round((df.isna().mean()*100).sort_values(ascending=False), 2)).astype(str) + ' %'

pricesshipping        39.74 %
pricesavailability    13.19 %
pricescondition        9.61 %
pricesmerchant         5.29 %
pricesamountmax         0.0 %
pricescurrency          0.0 %
pricesdateseen          0.0 %
pricesamountmin         0.0 %
pricesissale            0.0 %
brand                   0.0 %
categories              0.0 %
dateadded               0.0 %
dateupdated             0.0 %
primarycategories       0.0 %
sourceurls              0.0 %
weight                  0.0 %
dtype: object

In [ ]:
# Checking for missing values count
df.isna().sum().sort_values(ascending=False)

pricesshipping        5799
pricesavailability    1925
pricescondition       1403
pricesmerchant         772
pricesamountmax          0
pricescurrency           0
pricesdateseen           0
pricesamountmin          0
pricesissale             0
brand                    0
categories               0
dateadded                0
dateupdated              0
primarycategories        0
sourceurls               0
weight                   0
dtype: int64

## Step 3 — Remove Duplicates

In [ ]:
# Removing duplicate rows
df.drop_duplicates(inplace=True)
print("Duplicates remaining:", df.duplicated().sum())

Duplicates remaining: 0

In [ ]:
# Checking the number of unique values in each column
unique_counts = df.nunique().sort_values(ascending=False)
for col, val in unique_counts.items():
    print(f"{col}: {val}") 
    print('-'*25)

pricesdateseen: 6984
-------------------------
pricesamountmin: 4907
-------------------------
pricesamountmax: 4697
-------------------------
pricesmerchant: 1558
-------------------------
categories: 1199
-------------------------
sourceurls: 1192
-------------------------
dateadded: 1176
-------------------------
dateupdated: 1045
-------------------------
weight: 805
-------------------------
brand: 309
-------------------------
pricesshipping: 212
-------------------------
pricescondition: 18
-------------------------
pricesavailability: 17
-------------------------
primarycategories: 6
-------------------------
pricescurrency: 5
-------------------------
pricesissale: 2
-------------------------

In [ ]:
# Create target: average price
df['avg_price'] = (df['pricesamountmax'] + df['pricesamountmin']) / 2

## Step 4 — Feature Engineering: Source URL → Platform

In [ ]:
from urllib.parse import urlparse

def extract_platform_name(url):
    try:
        first_url = str(url).strip().split(',')[0].strip()                     # Get the first URL from the comma-separated list (if there are multiple)
        parsed = urlparse(first_url)                                           # Parse the URL into components (netloc, path)
        hostname = parsed.netloc or parsed.path                                # Use netloc (www.amazon.com) if available, otherwise fall back to path (missing scheme case)
        platform = hostname.split('.')                                         # Split hostname into parts (['reviews', 'bestbuy', 'com'])
        if len(platform) >= 2:
            platform = platform[-2]                                            # Take second-to-last part to get main domain (e.g., 'bestbuy' from 'reviews.bestbuy.com')
        else:
            platform = platform[0]                                             # If only one part exists (no dots), use it directly
            
        return platform.lower().strip() if platform else 'Unknown'             
    except:
        return 'Unknown'                                                       

df['platform'] = df['sourceurls'].apply(extract_platform_name)  
df.drop(columns=['sourceurls'], inplace=True)                    
print(df['platform'].value_counts())

platform
bestbuy                                                        6571
walmart                                                        2264
please use a view that flattens this field to see this data    1522
amazon                                                         1368
bhphotovideo                                                   1039
ebay                                                            874
target                                                          205
frys                                                            200
homedepot                                                       144
barcodable                                                       70
cdw                                                              42
kmart                                                            41
upccodesearch                                                    37
asus                                                             35
lowes                                                            34
hd radio and siriusxm ready"                                     27
overstock                                                        18
lazada                                                           15
officedepot                                                      13
abt                                                              13
16gb storage                                                     12
kohls                                                             9
hd radio                                                          6
wynit                                                             5
sears                                                             4
newegg                                                            3
co                                                                3
Name: count, dtype: int64

In [ ]:
px.histogram(df,x='platform',title='Distribution of Platforms',category_orders={'platform': df['platform'].value_counts().index},color_discrete_sequence=['#FF6692'])

## Step 5 — Date Columns → Year / Month / Day Features

In [ ]:
def process_dates(df):
    cols_to_fix = ['dateadded', 'dateupdated', 'pricesdateseen']
    for col in cols_to_fix:
        if col in df.columns:
            date = df[col].astype(str).str.split(',').str[0]                                          # Take only the first date if there are multiple dates
            date = date.str.replace('Z','',regex=False).str.replace('T',' ',regex=False)              # Remove unwanted characters
            df[col] = pd.to_datetime(date, errors='coerce', utc=True)                                 # Convert to datetime
            
            if pd.api.types.is_datetime64_any_dtype(df[col]):                                         # Check if conversion to datetime was successful
                df[col] = df[col].dt.tz_convert(None)                                                 # Remove timezone information (+00:00)
                df[f'{col}_year']  = df[col].dt.year
                df[f'{col}_month'] = df[col].dt.month_name()
                df[f'{col}_day']   = df[col].dt.day
    return df

df = process_dates(df)
df.drop(columns=['dateadded', 'dateupdated', 'pricesdateseen'], inplace=True)
df.head()

,pricesamountmax,pricesamountmin,pricesavailability,pricescondition,pricescurrency,pricesissale,pricesmerchant,pricesshipping,brand,categories,primarycategories,weight,avg_price,platform,dateadded_year,dateadded_month,dateadded_day,dateupdated_year,dateupdated_month,dateupdated_day,pricesdateseen_year,pricesdateseen_month,pricesdateseen_day
0,104.99,104.99,Yes,New,USD,False,Bestbuy.com,NaN,Sanus,"Audio & Video Accessories,TV Mounts,TV Accesso...",Electronics,32.8 pounds,104.990,amazon,2015,April,13,2018,May,12,2017,March,30
1,69.00,64.99,In Stock,New,USD,True,Walmart.com,Expedited,Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",Electronics,14 pounds,66.995,bestbuy,2015,May,18,2018,June,13,2017,December,14
2,69.00,69.00,In Stock,New,USD,False,Walmart.com,Expedited,Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",Electronics,14 pounds,69.000,bestbuy,2015,May,18,2018,June,13,2017,September,8
3,69.99,69.99,Yes,New,USD,False,Bestbuy.com,NaN,Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",Electronics,14 pounds,69.990,bestbuy,2015,May,18,2018,June,13,2017,October,10
4,66.99,66.99,Yes,New,USD,False,Bestbuy.com,NaN,Boytone,"Stereos,Portable Bluetooth Speakers,TV, Video ...",Electronics,14 pounds,66.990,bestbuy,2015,May,18,2018,June,13,2017,August,28

In [ ]:
px.histogram(df,x='pricesdateseen_year',y='avg_price',title='Price Trend Over Time',category_orders={'pricesdateseen_year': df['pricesdateseen_year'].value_counts().index},color_discrete_sequence=["#6B66FF"])

In [ ]:
px.histogram(df,x='pricesdateseen_month',y='avg_price',title='Price Trend Over Time',category_orders={'pricesdateseen_month': df['pricesdateseen_month'].value_counts().index},color_discrete_sequence=["#7DFF66"])

## Step 6 — Clean Weight Column (→ kg)

In [ ]:
def clean_weight(value):
    if pd.isna(value): 
        return None
    value = str(value).lower().strip()
    number = ''                                                   # Initialize an empty string to extract the numeric part of the value
    for char in value:                                           
        if char.isdigit() or char == '.':                         # After looping : Keep digits and the decimal point
            number += char                                        # Add the character to the number string
        else: 
            break
    if number == '': 
        return None
    number = float(number)
    if 'lb' in value or 'pound' in value: 
        return round(number * 0.453592, 3)
    elif 'oz' in value or 'ounce' in value: 
        return round(number * 0.0283495, 3)
    elif 'g' in value: 
        return round(number * 0.001, 3)
    return None

df['weight_kg'] = df['weight'].apply(clean_weight)
df.drop(columns=['weight'], inplace=True)
print(df['weight_kg'].value_counts())

weight_kg
0.454      341
0.045      221
0.907      205
2.041      170
0.068      143
0.227      143
0.544      141
0.009      138
3.629      136
1.343      135
1.814      134
0.159      131
0.635      131
0.499      130
0.680      126
0.181      121
0.476      120
0.091      117
0.998      110
1.361      108
0.816      106
0.281      105
0.113       98
0.748       97
2.268       93
0.340       90
13.789      84
0.649       84
0.136       83
0.306       83
0.005       82
5.080       81
0.041       81
1.179       79
0.283       79
0.023       78
0.318       77
0.726       76
0.001       76
1.588       73
0.088       71
1.370       71
7.983       70
0.272       66
0.320       66
17.917      65
0.018       62
0.002       62
1.497       61
0.567       61
0.125       61
0.249       60
0.204       60
2.722       59
2.585       58
2.631       58
2.495       57
1.905       57
0.585       57
13.608      56
6.804       56
4.990       55
0.295       54
9.979       54
0.299       54
0.060       54
10.478      53
1.089       53
24.086      53
0.290       52
0.184       52
1.610       52
0.054       50
0.027       50
1.406       49
0.086       49
0.245       48
2.300       48
0.953       48
0.921       48
2.812       47
19.006      47
1.724       47
26.490      46
0.119       46
34.110      45
24.721      45
9.389       45
9.435       45
0.445       45
0.209       44
2.245       44
0.093       43
2.699       43
36.197      43
0.363       43
5.670       43
0.386       42
0.431       42
10.523      42
0.247       42
3.901       41
2.177       41
0.196       41
1.134       40
0.286       40
0.168       39
24.585      39
0.794       38
9.525       38
1.152       37
8.119       37
1.225       37
12.002      37
0.377       36
0.277       36
23.451      36
14.696      36
0.036       35
0.261       35
0.130       35
2.903       35
0.553       34
0.344       34
11.793      34
1.800       34
2.223       34
0.150       34
7.257       34
0.082       33
5.398       33
8.528       33
8.482       33
8.101       33
0.167       33
8.233       32
6.305       32
2.948       32
18.597      32
0.717       32
0.862       32
3.856       31
2.767       31
1.678       31
0.170       31
0.381       31
2.676       31
31.888      31
10.795      31
1.996       31
2.313       30
2.404       30
3.488       30
0.350       30
0.032       30
1.247       30
1.746       30
0.099       29
9.707       29
3.538       29
1.501       29
3.175       29
0.003       29
0.231       28
0.434       28
0.198       28
9.163       28
1.950       28
0.400       28
1.315       27
0.590       27
28.486      27
0.011       27
0.395       26
0.017       26
5.443       26
1.061       26
28.803      26
3.810       26
26.399      26
4.082       26
1.542       25
1.429       25
6.441       25
0.218       25
6.350       25
0.176       25
0.153       25
0.186       25
0.059       25
26.717      25
2.087       25
7.666       25
3.583       24
0.415       24
3.130       24
6.985       23
7.711       23
0.028       23
10.206      23
28.894      23
0.885       23
0.975       23
5.361       22
79.379      22
11.204      22
15.513      22
4.536       22
0.467       22
42.003      22
0.013       22
25.719      22
1.701       22
41.277      22
0.096       21
0.612       21
1.860       20
22.680      20
16.103      20
12.610      20
0.771       20
0.270       20
0.408       20
4.672       20
0.875       20
3.152       20
1.928       20
1.320       20
0.105       20
0.472       20
158.757     19
0.453       19
3.066       19
3.266       19
4.037       19
4.218       19
9.571       19
8.618       19
6.396       19
0.422       19
0.116       18
13.998      18
8.300       18
8.709       18
24.948      18
7.802       18
0.694       18
0.416       18
12.156      18
2.994       18
0.007       17
0.190       17
24.403      17
16.420      17
1.102       17
1.202       17
0.040       17
1.960       17
5.307       17
0.135       17
0.241       17
8.301       17
0.104       17
18.602      17
0.275       17
2.132       17
2.649       16
1.111       16
0.322       16
0.107       16
2.241       16
11.476      16
0.111       16
9.072       16
0.195       16
2.359       16
1.864       15
0.898       15
4.763       15
0.420       15
0.310       15
6.486       15
4.445       15
7.484       15
2.449       15
0.451       15
0.145       15
6.169       15
14.787      15
1.025       15
8.550       15
6.917       15
8.165       15
16.329      15
0.043       15
11.839      14
3.107       14
0.399       14
1.479       14
0.020       14
7.394       14
0.490       14
5.897       14
5.987       14
3.221       14
3.674       14
0.599       14
0.110       14
27.216      14
0.930       13
1.001       13
2.182       13
0.127       13
16.465      13
0.437       13
0.640       13
4.001       13
8.437       13
7.530       13
23.768      13
4.604       12
0.798       12
30.844      12
32.341      12
5.579       12
0.244       12
1.402       12
0.435       12
0.896       12
5.148       12
22.045      12
4.627       12
3.800       12
6.668       12
0.354       12
2.350       12
11.698      11
1.270       11
7.475       11
0.163       11
7.212       11
0.051       11
34.019      11
8.981       11
3.992       11
7.770       11
3.778       11
2.808       11
0.665       11
2.250       11
0.079       11
13.109      11
2.622       11
0.671       11
0.703       10
0.676       10
3.402       10
0.391       10
14.515      10
2.159       10
0.238       10
0.721       10
7.076       10
0.706       10
0.304       10
3.434       10
15.422      10
10.160      10
8.193       10
2.454       10
10.886      10
18.008      10
4.128        9
0.037        9
24.494       9
6.713        9
13.154       9
1.451        9
1.383        9
1.048        9
0.106        9
18.507       9
0.540        9
11.884       9
5.942        9
0.224        9
0.572        9
38.873       9
11.022       9
8.001        9
0.057        9
0.004        9
1.887        9
0.014        9
37.195       9
0.142        9
74.480       9
0.255        9
18.098       9
1.043        8
15.921       8
0.789        8
1.520        8
14.016       8
0.077        8
0.044        8
0.463        8
1.107        8
3.311        8
1.352        8
1.787        8
11.294       8
12.020       8
18.416       8
5.851        7
63.503       7
0.301        7
3.084        7
0.000        7
0.984        7
0.026        7
12.111       7
20.003       7
0.180        7
0.394        7
11.703       7
14.470       7
0.254        7
1.438        7
14.878       7
6.078        7
18.824       7
0.561        6
10.024       6
0.371        6
0.658        6
4.173        6
4.581        6
18.189       6
3.756        6
0.033        6
0.210        6
0.008        6
12.927       6
57.606       6
0.172        6
0.179        6
6.214        6
0.182        6
26.898       6
0.031        6
14.061       6
0.309        6
0.313        6
12.383       6
14.424       6
3.569        5
0.085        5
2.608        5
6.260        5
27.397       5
19.595       5
0.240        5
17.010       5
2.400        5
0.268        5
6.940        5
0.369        5
0.626        5
0.535        5
0.100        5
0.308        5
4.899        5
2.858        5
0.147        5
2.499        5
13.381       5
7.439        5
0.428        5
43.998       5
68.039       4
0.034        4
7.756        4
0.481        4
8.305        4
16.842       4
1.769        4
113.398      4
8.192        4
23.405       4
0.380        4
0.062        4
0.303        4
1.796        4
0.122        4
14.202       4
0.800        4
34.972       4
0.358        4
0.894        4
1.220        4
0.414        4
13.018       4
0.148        4
11.340       4
0.880        4
21.001       4
1.397        4
0.390        4
10.297       3
0.123        3
8.800        3
0.689        3
0.330        3
0.349        3
1.066        3
10.070       3
12.428       3
2.173        3
0.751        3
3.016        3
21.999       3
35.426       3
0.221        3
0.118        3
0.090        3
7.734        2
0.074        2
0.103        2
5.348        2
0.230        2
1.139        2
0.108        2
0.417        2
0.522        2
15.785       2
5.625        2
30.391       2
7.121        2
0.064        2
1.021        2
6.895        2
29.756       2
1.565        2
3.651        2
3.039        2
0.332        2
20.684       1
1.338        1
3.742        1
0.889        1
74.843       1
Name: count, dtype: int64

In [ ]:
px.histogram(df,x='weight_kg',title='Distribution of Platforms',category_orders={'platform': df['platform'].value_counts().index},color_discrete_sequence=['#FF6692'])

## Step 7 — Clean Shipping Column

In [ ]:
def label_shipping(value):
    if pd.isna(value): 
        return 'Unknown'
    val = str(value).lower().strip()
    
    if any(w in val for w in ['free','expedited','prime','two-day','2-day']):        # 'any' --> returns True if any of the keywords are found in the string
        return 'Free'
    elif any(w in val for w in ['standard','value']): 
        return 'Standard'
    elif any(w in val for w in ['freight','cargo']): 
        return 'Freight'
    
    match = re.search(r'\d+\.?\d*', val)                                             # If no keyword matched, look for a numeric amount in the string
    if match:
        amount = float(match.group())
        if amount == 0:
            return 'Free'
        else: 
            return 'Paid'
    return 'Paid'

df['shipping_type'] = df['pricesshipping'].apply(label_shipping)
shipping_dummies = pd.get_dummies(df['shipping_type'], prefix='ship')                # Applying One-hot encoder
df = pd.concat([df, shipping_dummies], axis=1)
df.drop(columns=['pricesshipping'], inplace=True)
print(df['shipping_type'].value_counts())

shipping_type
Free        6088
Unknown     5781
Standard    2228
Paid         334
Freight      143
Name: count, dtype: int64

In [ ]:
ship = df['shipping_type'].value_counts().head(5).reset_index()
px.bar(ship, x='shipping_type',y='count',text='count', title='Distribution of Shipping Types', color_discrete_sequence=['#19D3F3'])

## Step 8 — Clean Merchant Column

In [ ]:
df['pricesmerchant'].unique()
df['pricesmerchant'].value_counts()

pricesmerchant
Bestbuy.com                                                              4448
bhphotovideo.com                                                         2744
Walmart.com                                                              1105
Amazon.com                                                                396
Beach Camera                                                              307
AMI Ventures Inc                                                          107
buydig                                                                     88
Focus Camera                                                               88
Best Buy                                                                   78
Beach Audio Inc                                                            72
echo-and-optics                                                            53
World Wide Stereo                                                          52
Newegg                                                                     50
UnbeatableSale                                                             49
BuyVPC                                                                     45
DealClock                                                                  45
gear4less                                                                  43
Amazon                                                                     42
Electronics Expo (Authorized Dealer)                                       40
Video & Audio Center                                                       39
OneCall                                                                    38
Electronic Express                                                         37
electronic_express                                                         35
pcRUSH - Walmart.com                                                       33
Car Audio Closeout                                                         28
6ave                                                                       26
vipoutlet                                                                  25
homedepot.com                                                              24
antonline.com                                                              24
Dell.com                                                                   23
gadget-town                                                                22
OutletPC                                                                   22
Beach Audio Inc - Walmart.com                                              22
Tech For Less Inc                                                          22
wwstereo                                                                   21
Wholesale Connection                                                       21
Cameta Camera                                                              21
Sound of Tri-State                                                         20
Walts TV                                                                   19
extremenetwork                                                             19
Kmart                                                                      18
barterboxusa                                                               18
Focus Camera - Walmart.com                                                 18
VMInnovations                                                              18
DemProductSales                                                            18
VIPOUTLET                                                                  17
outletmp3                                                                  17
TigerDirect - Walmart.com                                                  16
bargainstation - Walmart.com                                               16
6Ave Express LLC                                                           16
applerevival                                                               16
redtagcamera                                                               16
best_buy                                                                   15
Beach Camera Same Day Shipping                                             15
eLGeo Electronics                                                          15
The Pixel Hub                                                              15
BuyVPC - Walmart.com                                                       15
focuscamera                                                                15
Technology Galaxy                                                          15
videoandaudiocenter                                                        15
thepixelhub                                                                14
My Goods                                                                   14
Audiosavings                                                               14
E-Warehouse-Deals                                                          14
tri-state-camera                                                           14
DiamondBuy                                                                 14
SaveTronix                                                                 14
Growkart                                                                   13
uShopMall                                                                  13
Limited Goods - Walmart.com                                                13
goldstar_tech                                                              13
easy-to-open packaging                                                     13
Beach Camera - Walmart.com                                                 13
ielectrica                                                                 12
photovideo4less                                                            12
newopenbox                                                                 12
SaveCentral, LLC                                                           12
17th St Photo Supply Inc                                                   12
Wayfair - Walmart.com                                                      11
Clover Hill                                                                11
Creative Audio                                                             11
autosounds4less                                                            11
www-sonicelectronix-com                                                    11
Adorama Camera                                                             11
ElectroCell                                                                10
tfldealz                                                                   10
Computer Brain                                                             10
electronicsliquidators                                                     10
Sears.com                                                                  10
superdealunlimited                                                         10
onecall                                                                    10
TEKENVY - Walmart.com                                                      10
wholesale_connection                                                       10
a1Components                                                               10
savecentral-outlet                                                         10
Hyper Microsystems, Inc.                                                   10
brandsmartusa                                                              10
HappEshopper                                                               10
Hippo-Deals                                                                 9
HPP Enterprises                                                             9
autosounds_warehouse                                                        9
CarAudioDistributors - Walmart.com                                          9
Overstock.com                                                               9
Sam Ash Music Direct                                                        9
Audiolab Stereo & Video Center                                              9
Adorama                                                                     9
Details                                                                     9
Made Technology                                                             9
JB Tool Sales                                                               9
aimusa                                                                      9
refurbforless                                                               9
Mega Retail Store - Walmart.com                                             8
ericy23                                                                     8
True Modern Electronics                                                     8
Marine Discount Center, LLC                                                 8
Alex Magic Electronics                                                      8
iigoldensunii                                                               8
beachaudio                                                                  8
Datavision Computer Video                                                   8
antonline - Walmart.com                                                     7
deals-all-year                                                              7
extremeelectronix                                                           7
HookedOnTronics                                                             7
Norman Camera Company                                                       7
evergreenpoint                                                              7
Hisense USA Corporation                                                     7
Hotelectronics                                                              7
GeekZilla                                                                   7
Photo-Zone                                                                  7
Panda Rover                                                                 7
Electronic Express - Walmart.com                                            7
ipadelectronics                                                             7
Circuit City - Walmart.com                                                  7
cametaauctions                                                              7
Simple Cell Inc                                                             7
VIP OUTLET                                                                  7
EZ Tech                                                                     7
AV Toy Store                                                                7
ProMax Commerce                                                             6
universe-deals                                                              6
outletpc                                                                    6
VM Innovations                                                              6
aSavings                                                                    6
Bluehaze                                                                    6
Googol Shop                                                                 6
pcRUSH                                                                      6
d.a.n.t_tech                                                                6
MA Trade LLC                                                                6
Echo and Optics                                                             6
eCopUSA                                                                     6
bigvalueinc                                                                 6
sando_distributions                                                         6
PT Etech                                                                    6
Mian Brothers Inc                                                           6
GRAMOPHONE (Authorized Dealer)                                              6
Wayfair                                                                     6
ETM Online Deals, LLC                                                       6
PT ELIFE LLC                                                                6
listenup                                                                    6
aapltree                                                                    6
tbdeals                                                                     6
nothingbutsavings                                                           6
PrimeDeal                                                                   6
Wayfair.com - Walmart.com                                                   6
iSave                                                                       6
OneCall - Walmart.com                                                       6
Electronics Expo - Walmart.com                                              6
Unbeatable Deals                                                            6
BidDeal                                                                     6
Amazon.ca                                                                   6
BargainStation.com - Walmart.com                                            6
DigitalShopper                                                              6
poppy9780                                                                   6
antonline                                                                   5
dwgreatdeals                                                                5
THS                                                                         5
West Coast Limited                                                          5
Amazing Cross Cloud Deals                                                   5
axxii                                                                       5
UnbeatableSale - Walmart.com                                                5
Deals Unlimited                                                             5
AUDIO WATT STORE                                                            5
TechZone                                                                    5
SCONTROLC                                                                   5
legendmicro-wholesale                                                       5
Santa Monica Wireless                                                       5
shopcelldeals                                                               5
WorldWide Distributors                                                      5
LG.com                                                                      5
sundown.one                                                                 5
candys-outlet-store                                                         5
gearbrokers                                                                 5
B and H Cellular Wholesale Inc.                                             5
buyvpc                                                                      5
blueboxsales                                                                5
hypermicrosystems                                                           5
electr0nicsrus                                                              5
Tech2Date                                                                   5
Always.Deals                                                                5
One Time Cell                                                               5
trd_digital                                                                 5
Monoprice Inc                                                               5
Amazing Deals Online                                                        5
Mobiles International LLC                                                   5
themacninja                                                                 5
blinq                                                                       5
Aztek Computers                                                             5
Bibbys electronics                                                          5
dealsfellow                                                                 4
Cymax - Walmart.com                                                         4
fanteller                                                                   4
Tri State Camera                                                            4
georgec4459                                                                 4
Olivabel                                                                    4
OneDealOutlet Online                                                        4
accurateitservice                                                           4
itreplay                                                                    4
BuyWise Corp.                                                               4
less.4.more                                                                 4
Rover Store, Inc.                                                           4
superior sales                                                              4
Electronics Expo                                                            4
[AIM USA]                                                                   4
Artio International                                                         4
look-here-buy-here                                                          4
Azano Inc                                                                   4
Video & Audio  Center                                                       4
Wayfair - Bestbuy.com                                                       4
ONE STOP SHOP                                                               4
great_retailers                                                             4
jaybrokers                                                                  4
tms.store                                                                   4
youbuyrite                                                                  4
Overstock                                                                   4
elektech.1                                                                  4
United Liquidators                                                          4
Audiovideodirect                                                            4
PIXIBYTES INC                                                               4
CalvinNHobbs                                                                4
Good Luck Bargains                                                          4
Nexit, Inc.                                                                 4
702-motoring                                                                4
jakejake25                                                                  4
mobileshark                                                                 4
gpscity                                                                     4
Pro AV Dealer                                                               4
MemoryC, Inc.                                                               4
Nationwide Distributor                                                      4
shopbargainworks                                                            4
El Chasqui USA Company                                                      4
AAAA UNIVERSE                                                               4
mrphotostore                                                                4
hanabeauty10                                                                4
E-TRONIX                                                                    4
Walmarked                                                                   4
Tech For Less Inc - Walmart.com                                             4

In [ ]:
def clean_merchant(name):
    if pd.isna(name): 
        return 'Other'
    name = str(name).lower().strip()
    if 'bestbuy' in name or 'best buy' in name: 
        return 'Best Buy'
    elif 'walmart' in name:
        return 'Walmart'
    elif 'amazon' in name: 
        return 'Amazon'
    elif 'bhphoto' in name: 
        return 'B&H Photo'
    elif 'ebay' in name: 
        return 'eBay'
    return 'Other'

df['merchant_clean'] = df['pricesmerchant'].apply(clean_merchant)

# Frequency Encoding
merchant_freq = df['merchant_clean'].value_counts().to_dict()
df['merchant_freq_encoded'] = df['merchant_clean'].map(merchant_freq)                         # Each merchant name is replaced by its frequency count using map()
df.drop(columns=['pricesmerchant'], inplace=True)
print(merchant_freq)

{'Other': 5455, 'Best Buy': 4534, 'B&H Photo': 2744, 'Walmart': 1395, 'Amazon': 446}

In [ ]:
px.histogram(df, x='merchant_clean', title='Distribution of Merchants', category_orders={'merchant_clean': df['merchant_clean'].value_counts().index}, color_discrete_sequence=['#FFA15A'])

## Step 9 — Clean Condition Column

In [ ]:
df['pricescondition'].unique()

array(['New', 'new', 'Seller refurbished', 'Used', 'pre-owned',
       'Refurbished', 'Manufacturer refurbished',
       'New other (see details)', 'refurbished',
       'New Kicker BT2 41IK5BT2V2 Wireless Bluetooth USB Audio System Black + Remote, Power Supply (volts, ampere): 24, 2.9, Square Reflex Subwoofer (in., mm): 6 x 6", Stereo Amp Power with DSP (watts): 50, App for customizing - KickStart, Remote Control Included, Height x Width x Depth (in, mm): 8.87" x 19" x 9.14", Frequency Response (Hz): 24-20k, +-3dB, Woofer (in., cm): 5", 1 Year Manufacturer Warranty, Item Weight: 13.85 lbs., USB Port, Compatible with: Bluetooth-enabled devices, Aux-in, Speaker Design: 2-Way Full-Range, Bluetooth wireless streaming, Condition: Brand New!, Tweeter (in., cm): 3/4"',
       '5/16" Ring Terminal, 3 ft. 8 GA Black Ground Cable, 6 ft. Split Loom Tubing, Depth: 6.5" (165mm) (top) 11.2" (285mm) (bottom), Item Weight: 18.5 lbs., Frequency Response 25Hz - 500Hz, Line Output, Max Power: 1100 Watt x 1 Channel @ 2 Ohm, 30 ft. Speaker Wire, Boss Illuminated Logo, Height: 12.8" (325mm), (3) Rubber Grommets, Item Weight: 2 lbs., Size 10", 20 ft. 8 GA Red Power Cable, Ported enclosure for greater output and deeper bass, 2 Ohm Stable, Class A/B, Voice Coil Size 2", Black rubber surround, Nominal Impedance 4 ohm, Rugged fiberboard construction with thick carpet covering, Warranty: 1 Year Manufacturer Warranty, MOSFET Power, Weight: 6 lbs, Width: 17.7" (450mm), Condition: Brand New!, Low Pass Crossover, List item, RMS Power: 250 Watt x 1 Channel @ 4 Ohm, Remote Bass Control Included!, 1/4" Ring Terminal, 16 ft. 18 GA Blue Turn-On Wire, Peak Power: 500 Watts, Competition High Quality Fuse Holder, Condition: BRAND NEW!, Product Condition: Brand New, RMS Power: 175 Watts, Aluminum woofer cone, THD: 0.01%, 1 Year Manufacturer Warranty, Dimensions: 10-7/16" (W) x 2-1/4" (H) x 9-1/8" (L), #10 Ring Terminal, 20 ft. High Performance Black RCA, SPL (db @ 1w/1m) 88dB, New Dual SBX101 10" 500 Watts Car Audio Subwoofer Sub + Ported Sub Enclosure, (20) 4" Wire Ties',
       'Top-mount Depth: 3-1/8", 2) New Kicker 41KSC6934 6x9" 3-Way 300 Watt Car Audio Coaxial Speakers KSC693, Item Weight: 8 lbs., 3/4" silk dome tweeter, 4 ohms impedance, Tweeter Magnet: Neodymium, Tweeter Protrusion: 3/16, Rubber surround, Peak: 300 watts, Mounting Hole Diameter: 5-11/16x8-7/16", 1 Year Manufacturer Warranty, RMS: 150 watts, Bottom Mount Depth: 3-5/8", Grilles: Yes, Frequency Response: 30-21,000 Hz, Sensitivity: 92dB, Polypropylene midwoofer, Condition: Brand New!',
       'Product warranty: 1-year warranty, Top-mount Depth: 3-1/8", Item Weight: 8 lbs., 3/4" silk dome tweeter, 4 ohms impedance, Tweeter Magnet: Neodymium, Tweeter Protrusion: 3/16, Rubber surround, Peak: 300 watts, Mounting Hole Diameter: 5-11/16x8-7/16", RMS: 150 watts, Bottom Mount Depth: 3-5/8", Grilles: Yes, Kicker 41KSC6934 6x9" 3-Way 300 Watt Car Audio Coaxial Speakers KSC693, Frequency Response: 30-21,000 Hz, Quantity: 4 speakers, Sensitivity: 92dB, Polypropylene midwoofer, Condition: Brand New!',
       nan,
       'Magnet - Neodymium, SearsCondition - Refurbished, Refresh Rate - 4Hz - 100kHz, Headphone Type - Over the Head, Driver Unit - 70mm, Power Handling (Watts) - 2000mW, Plug Type - 3.5mm, Audio Accessories - Headphones, Headphone Uses - Audiophile; iPod, Color - Black; Black, Impedance - 70 ohm, Cable Length - 6 - 6.99 Feet; 9 - 9.99 Feet, Sensitivity - 102dB, Headphone Styles - Over-ear',
       'For parts or not working', 'Brand New',
       'iPod Skip/2 Speed Search Function, Surround: Cloth, Random/Repeat Play, Loudness, Impedance 4 ohms, Front AUX & USB Interface with slide protection cover, iPod/iPhone Direct Connection with Optional cable*1, FM Stereo/Mono Selector, Bass Boost, Frequency Response: 35 Hz - 20k Hz, Variable Color Illumination, General Features, Item Weight: 2 lbs., CD-R/CD-RW Compatible, 13 Digit 1.5Line LCD Display, Sirius XM (SXV100/200/300) Ready, RBDS with Radio Text, USB Features, Sensitivity: 92 dB / W / m, Built-in LPF/HPF, Equalizer (13Band), CD Text Ready, Subwoofer Level Adjustable, Dimmer Control Function (Manual/Set by timer), Magnet: Ferrite, Weight of Magnet (Woofer): 0.2lbs, Rotary Encoder and Direct Key (TEL) for easy operation, Android Rapid Charge, MP3, WMA, AAC, WAV, FLAC Decoder with ID-3 Tag Display, Drive Change (For Android or Card Reader), Diaphragm: PP Cone, RMS Power: 30W, Digital Clock (12H), MP3, WMA, AAC Decoder with ID-3 Tag Display, 1 Year VMInnovations Warranty, AME (Automatic Memory Entry), 0-bit Mute, Condition: Brand New!, Wireless Music Browsing, Basket Steel: Black, Dual Phone Connection, Drive EQ, Part Number: DPX502BT, Up/Down Seek Tuning, Backup Memory for Tuner Preset, Folder Name Manual Search Function without Stopping Audio-play, Mounting Depth: 1-11/16inch, Stage EQ, Condition: New, Multi language(English, Spanish), FM/AM 24 Station Presets (18FM, 6AM), Kenwood sound reconstruction, restores musical to compressed music, Cutout Diameter: 4-7/8inch, System Q, Woofer: 6-1/2inch PP Cone, Android Music Playback, CD Features, MP3/WMA/AAC/WAV/FLAC Files Playback with ID-3 Tag Display, MAX Power: 300W, Audio Features, Maximum Output Power : 50W x 4 (MOSFET Power IC), 3 Preout (2.5V), Tuner Features, Pandora / iHeart Radio App Ready (iPhone App)',
       'Pioneer 10" TS-SW2502 Pre-Load Shallow Subwoofer Enclosure, Frequency Response: 93dB, Oversized Cone Structure, Compact-Space Saving Design, Cone Material: MICA injection-molded resin, Part Number: TS-SWX2502 (TSSWX2502), Impedance: Single 4 Ohm, Enclosure Dimensions: 18-5/8" x 13 7/8" x 6", RMS Power: 300 Watts, Max Power: 1200 Watts, 1 Year Warranty, Condition: Brand New!'],
      dtype=object)

In [ ]:
def classify_condition(value):
    if pd.isna(value) or str(value).strip().lower() in ['nan', '', 'none', 'unknown']:
        return 'Unknown'
    
    val = str(value).lower().strip()
    
    if any(w in val for w in ['refurbished', 'reconditioned', 'remanufactured']):
        return 'Refurbished'
    elif any(w in val for w in ['used', 'pre-owned', 'for parts', 'not working']):
        return 'Used'
    elif any(w in val for w in ['new', 'brand new', 'sealed', 'unopened']):
        return 'New'
    
    return 'Unknown' 

df['pricescondition'] = df['pricescondition'].apply(classify_condition)
print(df['pricescondition'].value_counts())

pricescondition
New            12489
Unknown         1394
Used             461
Refurbished      230
Name: count, dtype: int64

In [ ]:
condition_order = [['Used', 'Refurbished', 'New', 'Unknown']]                        # Ordinal Encoding
encoder = OrdinalEncoder(categories=condition_order)                                 
df['pricescondition_encoded'] = encoder.fit_transform(df[['pricescondition']])       
df['pricescondition_encoded'] = df['pricescondition_encoded'] + 1                    # Shift values to make New=3, Refurbished=2, Used=1

px.histogram(df, x='pricescondition', title='Distribution of Product Conditions', color_discrete_sequence=['#00CC96'])

## Step 10 — Clean Availability Column

In [ ]:
df['pricesavailability'].unique()

array(['Yes', 'In Stock', 'TRUE', 'undefined', 'yes', 'Out Of Stock',
       'Special Order', 'No', 'More on the Way', 'sold', 'FALSE',
       'Retired', '32 available', '7 available', nan, 'Limited Stock',
       'Discontinued', 'More Coming Soon'], dtype=object)

In [ ]:
def clean_availability(value):
    if pd.isna(value) or str(value).lower() in ['undefined','nan']: 
        return 'Unknown'
    val = str(value).lower().strip()
    if any(x in val for x in ['yes', 'in stock', 'true']):
        return 'Available'
    out_of_stock = ['no','false','out of stock','sold','retired']
    if any(w in val for w in out_of_stock): 
        return 'Out Of Stock'
    # Limited / Special / Coming Soon
    elif any(x in val for x in ['special order', 'more on the way','limited stock', 'coming soon', 'available']):
        return 'Limited/Coming Soon'
    # Discontinued / Retired
    elif any(x in val for x in ['retired', 'discontinued']):
        return 'Discontinued'

df['is_in_stock'] = df['pricesavailability'].apply(clean_availability)
df.drop(columns=['pricesavailability'], inplace=True)
print(df['is_in_stock'].value_counts())

is_in_stock
Available              12031
Unknown                 1965
Limited/Coming Soon      305
Out Of Stock             268
Discontinued               5
Name: count, dtype: int64

In [ ]:
px.histogram(df, x='is_in_stock', title='Stock Availability', color_discrete_sequence=['#AB63FA'])

## Step 11 —Brand Column

In [ ]:
brand_counts = df['brand'].value_counts().head(10).reset_index()
px.bar(brand_counts,x='brand',y='count',text='count',title='Top 10 Brands Distribution',color_discrete_sequence=['#EF553B'])

## Step 12 — Clean Categories Column

In [ ]:
# Split the 'categories' column by commas and remove any extra spaces to create a list of categories for each product
df['categories_list'] = df['categories'].str.split(',').apply(lambda x: [i.strip() for i in x])

# Extract the first category from the list, or 'Unknown' if the list is empty
df['first_category']  = df['categories_list'].apply(lambda x: x[0] if len(x) > 0 else 'Unknown')

def detect_category(cat):
    cat = str(cat).lower().strip()  
    
    if any(k in cat for k in ['computer','laptop','tablet']):          
        return 'Computers'
    elif any(k in cat for k in ['tv','ultra hd','flat screen','smart tv']): 
        return 'TVs'
    elif any(k in cat for k in ['audio','speaker','headphone','soundbar','subwoofer']): 
        return 'Audio & Speakers'
    elif any(k in cat for k in ['camera','photo','dslr','mirrorless']): 
        return 'Cameras'
    elif any(k in cat for k in ['phone','mobile','ipod','mp3']):        
        return 'Phones & Music Players'
    elif any(k in cat for k in ['office','tool','printer']):            
        return 'Office & Tools'
    else:                                                               
        return 'Other' 

df['first_category'] = df['first_category'].apply(detect_category)

# Frequency Encoding: count how many times each category appears
cat_freq = df['first_category'].value_counts().to_dict()

# Map the frequency count to a new column
df['category_freq_encoded'] = df['first_category'].map(cat_freq)

# Print each category with its count
for cat, cnt in cat_freq.items():
    print(f"{cat}: {cnt}")

Computers: 4475
Other: 4311
Audio & Speakers: 1912
TVs: 1730
Cameras: 1418
Phones & Music Players: 397
Office & Tools: 331

In [ ]:
px.histogram(df, x='first_category', title='Distribution of Main Categories', color_discrete_sequence=['#636EFA'],text_auto=True)

## Step 13 — PrimaryCategories

In [ ]:
df['primarycategories'] = df['primarycategories'].astype(str)
print(df['primarycategories'].value_counts())
print("Missing:", df['primarycategories'].isna().sum())

primarycategories
Electronics              14464
Electronics,Furniture       61
 Apple CarPlay              27
 Intel Celeron              12
 Siri Eyes Free              6
Electronics,Media            4
Name: count, dtype: int64
Missing: 0

In [ ]:
def clean_primary_category(val):
    val = val.strip()                       
    if ',' in val:                            
        val = val.split(',')[1].strip()
    return val

df['primarycategories_clean'] = df['primarycategories'].apply(clean_primary_category)
print(df['primarycategories_clean'].value_counts())

primarycategories_clean
Electronics       14464
Furniture            61
Apple CarPlay        27
Intel Celeron        12
Siri Eyes Free        6
Media                 4
Name: count, dtype: int64

In [ ]:
ohe_df = pd.get_dummies(df['primarycategories_clean'], prefix='primarycategories')
df = pd.concat([df, ohe_df], axis=1)
print(df.filter(like='primarycategories').head())

  primarycategories primarycategories_clean  primarycategories_Apple CarPlay  \
0       Electronics             Electronics                            False
1       Electronics             Electronics                            False
2       Electronics             Electronics                            False
3       Electronics             Electronics                            False
4       Electronics             Electronics                            False

   primarycategories_Electronics  primarycategories_Furniture  \
0                           True                        False
1                           True                        False
2                           True                        False
3                           True                        False
4                           True                        False

   primarycategories_Intel Celeron  primarycategories_Media  \
0                            False                    False
1                            False                    False
2                            False                    False
3                            False                    False
4                            False                    False

   primarycategories_Siri Eyes Free
0                             False
1                             False
2                             False
3                             False
4                             False

In [ ]:
ship = df['primarycategories_clean'].value_counts().head(5).reset_index()
px.bar(ship, x='primarycategories_clean',y='count',text='count', title='Distribution of Shipping Types', color_discrete_sequence=['#19D3F3'])

In [ ]:
# نربط الـ OHE بالسعر
avg_prices = []

for col in ohe_df.columns:
    avg_price = df[df[col] == 1]['avg_price'].mean()
    avg_prices.append((col, avg_price))

avg_df = pd.DataFrame(avg_prices, columns=['Category', 'Avg Price'])

# تنظيف الاسم
avg_df['Category'] = avg_df['Category'].str.replace('primarycategories_', '')

# ترتيب
avg_df = avg_df.sort_values(by='Avg Price', ascending=False)

fig = px.bar(
    avg_df,
    x='Category',
    y='Avg Price',
    text='Avg Price',
    title='Average Price by Category',
    color_discrete_sequence=['#FF6692']
)

fig.show()

In [ ]:
df.drop(columns=['primarycategories', 'primarycategories_clean'], inplace=True)

## Step 13 — Price Sale Column

In [ ]:
Sale = df['pricesissale'].value_counts().reset_index()
px.bar(Sale,x='pricesissale',y='count',text='count',title='Sale Status Distribution',color_discrete_sequence=['#EF553B'])

## Step 14 — Currency Column

In [ ]:
# 🔹 Exchange Rates
exchange_rates = {
    'USD': 1.0,
    'EUR': 1.17,
    'GBP': 1.25,
    'CAD': 0.74,
    'SGD': 0.74
}

# 🔹 Map currencies to rates
df['rate'] = df['pricescurrency'].map(exchange_rates)

# 🔹 Handle missing currencies (default = 1)
df['rate'] = df['rate'].fillna(1)

# 🔹 Convert prices to USD
df['pricesamountmax_usd'] = df['pricesamountmax'] * df['rate']
df['pricesamountmin_usd'] = df['pricesamountmin'] * df['rate']

# 🔹 Create average price in USD
df['avg_price_usd'] = (df['pricesamountmax_usd'] + df['pricesamountmin_usd']) / 2

# 🔹 Drop helper column (optional)
df.drop(columns=['rate'], inplace=True)

# 🔹 Check result
df_prices = pd.concat([
    df['pricesamountmax'],
    df['pricesamountmax_usd'],
    df['avg_price_usd']
], axis=1)

print(df_prices.head())
print(df[['pricescurrency','pricesamountmax','pricesamountmax_usd','avg_price_usd']].head())

   pricesamountmax  pricesamountmax_usd  avg_price_usd
0           104.99               104.99        104.990
1            69.00                69.00         66.995
2            69.00                69.00         69.000
3            69.99                69.99         69.990
4            66.99                66.99         66.990
  pricescurrency  pricesamountmax  pricesamountmax_usd  avg_price_usd
0            USD           104.99               104.99        104.990
1            USD            69.00                69.00         66.995
2            USD            69.00                69.00         69.000
3            USD            69.99                69.99         69.990
4            USD            66.99                66.99         66.990

In [ ]:
df['pricescurrency'].unique()

array(['USD', 'CAD', 'SGD', 'EUR', 'GBP'], dtype=object)

## Step 15 — Handle Outliers & Fill Missing Numerics

In [ ]:
fig = px.box(df,y='pricesamountmax',title='Max Price Distribution',color_discrete_sequence=["#8266FF"])
fig.show()

In [ ]:
fig = px.box(df,y='pricesamountmin',title='Min Price Distribution',color_discrete_sequence=["#FF6666"])
fig.show()

In [ ]:
fig = px.box(df,y='weight_kg',title='Weight Distribution',color_discrete_sequence=["#FF6666"])
fig.show()

In [ ]:
def outlier_percentage(series):
    series = series.dropna()
    Q1, Q3 = series.quantile(0.25), series.quantile(0.75)
    IQR    = Q3 - Q1
    outliers = series[(series < Q1 - 1.5*IQR) | (series > Q3 + 1.5*IQR)]
    return round(len(outliers) / len(series) * 100, 2)

outlier_report = {col: outlier_percentage(df[col])
                  for col in ['pricesamountmax','pricesamountmin','weight_kg']}
outlier_report

{'pricesamountmax': 11.63, 'pricesamountmin': 11.1, 'weight_kg': 14.45}

In [ ]:
# Fill missing numerics with median
df['pricesamountmax'] = df['pricesamountmax'].fillna(df['pricesamountmax'].median())
df['pricesamountmin'] = df['pricesamountmin'].fillna(df['pricesamountmin'].median())
df['weight_kg']       = df['weight_kg'].fillna(df['weight_kg'].median())

def remove_outliers(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    return df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]

df = remove_outliers(df, 'avg_price')

print(df[['pricesamountmax','pricesamountmin','avg_price','weight_kg']].describe())

       pricesamountmax  pricesamountmin     avg_price     weight_kg
count     12927.000000     12927.000000  12927.000000  12927.000000
mean        259.334645       252.207272    255.770959      3.206984
std         255.705394       245.939779    249.915530      8.602413
min           1.000000         1.000000      1.000000      0.000000
25%          73.060000        70.790000     72.375000      0.227000
50%         159.980000       153.990000    158.000000      0.717000
75%         365.000000       349.990000    359.990000      2.812000
max        1499.990000      1129.260000   1129.260000    158.757000

In [ ]:
# Confirm no missing values remain
(df.isna().mean()*100).sort_values(ascending=False).head(10)

pricesamountmax    0.0
pricesamountmin    0.0
pricescondition    0.0
pricescurrency     0.0
pricesissale       0.0
brand              0.0
categories         0.0
avg_price          0.0
platform           0.0
dateadded_year     0.0
dtype: float64

## Step 16 — Drop Remaining Raw / Unused Columns

In [ ]:
df.drop(columns=['categories','categories_list'],inplace=True, errors='ignore')
df['pricesissale'] = df['pricesissale'].astype(int)
print("Final shape:", df.shape)
df.head()
df.columns

Final shape: (12927, 39)

Index(['pricesamountmax', 'pricesamountmin', 'pricescondition',
       'pricescurrency', 'pricesissale', 'brand', 'avg_price', 'platform',
       'dateadded_year', 'dateadded_month', 'dateadded_day',
       'dateupdated_year', 'dateupdated_month', 'dateupdated_day',
       'pricesdateseen_year', 'pricesdateseen_month', 'pricesdateseen_day',
       'weight_kg', 'shipping_type', 'ship_Free', 'ship_Freight', 'ship_Paid',
       'ship_Standard', 'ship_Unknown', 'merchant_clean',
       'merchant_freq_encoded', 'pricescondition_encoded', 'is_in_stock',
       'first_category', 'category_freq_encoded',
       'primarycategories_Apple CarPlay', 'primarycategories_Electronics',
       'primarycategories_Furniture', 'primarycategories_Intel Celeron',
       'primarycategories_Media', 'primarycategories_Siri Eyes Free',
       'pricesamountmax_usd', 'pricesamountmin_usd', 'avg_price_usd'],
      dtype='object')

---
# 📊 Exploratory Data Analysis (EDA)

In [ ]:
# Average Price Distribution
px.histogram(df, x='avg_price', nbins=60, title='Distribution of Average Price',
             color_discrete_sequence=['#636EFA'])

In [ ]:
# Average price per merchant
merchant_price = df.groupby('merchant_clean')['avg_price'].mean().reset_index()

fig = px.bar(merchant_price, x='merchant_clean', y='avg_price',
             title="Average Price per Merchant", color='avg_price', color_continuous_scale='Oranges')
fig.show()

In [ ]:
# Count products per merchant
merchant_count = df.groupby('merchant_clean').size().reset_index(name='count')

fig = px.bar(merchant_count, x='merchant_clean', y='count',
             title="Number of Products per Merchant",color='count', color_continuous_scale='Reds')
fig.show()

In [ ]:
# Avg price by category
cat_price = df.groupby('first_category')['avg_price'].mean().sort_values(ascending=False).reset_index()
px.bar(cat_price, x='first_category', y='avg_price',
       title='Average Price by Category',
       labels={'avg_price':'Avg Price ($)','first_category':'Category'},
       color='avg_price', color_continuous_scale='Blues')

In [ ]:
fig = px.box(df, x='first_category', y='avg_price',
             title="Price Distribution per Category")
fig.show()

In [ ]:
# Avg price per condition
cond_price = df.groupby('pricescondition')['avg_price'].mean().reset_index()

fig = px.bar(cond_price, x='pricescondition', y='avg_price',
             title="Average Price by Condition",color='avg_price', color_continuous_scale='Reds')
fig.show()

In [ ]:
# Count condition
cond_count = df.groupby('pricescondition').size().reset_index(name='count')

fig = px.pie(cond_count, names='pricescondition', values='count',
             title="Product Condition Distribution",color_discrete_sequence=px.colors.qualitative.Set3)
fig.show()

In [ ]:
# Sale vs Not sale
sale_count = df.groupby('pricesissale').size().reset_index(name='count')

fig = px.pie(sale_count, names='pricesissale', values='count',
             title="Sale vs Non-Sale Products",color_discrete_sequence=px.colors.qualitative.Set3)
fig.show()

In [ ]:
# Sale vs Regular price
sale_price = df.groupby('pricesissale')['avg_price'].mean().reset_index()
sale_price['pricesissale'] = sale_price['pricesissale'].map({0:'Regular', 1:'Sale'})
px.bar(sale_price, x='pricesissale', y='avg_price',
       title='Sale vs Regular Price',
       labels={'avg_price':'Avg Price ($)','pricesissale':'Price Type'},
       color='avg_price', color_continuous_scale='Reds')

In [ ]:
# Availability count
avail_count = df.groupby('is_in_stock').size().reset_index(name='count')

fig = px.pie(avail_count, names='is_in_stock', values='count',
             title="Stock Availability",color_discrete_sequence=px.colors.qualitative.Set2)
fig.show()

In [ ]:
# Top brands avg price
brand_price = df.groupby('brand')['avg_price'].mean().sort_values(ascending=False).reset_index().head(10)
px.bar(brand_price, x='brand', y='avg_price',
       title='Average Price by Brand',
       labels={'avg_price':'Avg Price ($)','brand':'Brand'},
       color='avg_price', color_continuous_scale='Viridis')

In [ ]:
# Correlation heatmap (numerical features)
num_cols_all = df.select_dtypes(include='number').columns.tolist()
px.imshow(df[num_cols_all].corr(), title='Correlation Matrix — Numerical Features',
          color_continuous_scale='RdBu', color_continuous_midpoint=0)

---
# 🤖 Machine Learning
**Goal:** Predict the **average price** of an electronics product.

In [ ]:
df.head()

,pricesamountmax,pricesamountmin,pricescondition,pricescurrency,pricesissale,brand,avg_price,platform,dateadded_year,dateadded_month,dateadded_day,dateupdated_year,dateupdated_month,dateupdated_day,pricesdateseen_year,pricesdateseen_month,pricesdateseen_day,weight_kg,shipping_type,ship_Free,ship_Freight,ship_Paid,ship_Standard,ship_Unknown,merchant_clean,merchant_freq_encoded,pricescondition_encoded,is_in_stock,first_category,category_freq_encoded,primarycategories_Apple CarPlay,primarycategories_Electronics,primarycategories_Furniture,primarycategories_Intel Celeron,primarycategories_Media,primarycategories_Siri Eyes Free,pricesamountmax_usd,pricesamountmin_usd,avg_price_usd
0,104.99,104.99,New,USD,0,Sanus,104.990,amazon,2015,April,13,2018,May,12,2017,March,30,14.878,Unknown,False,False,False,False,True,Best Buy,4534,3.0,Available,Audio & Speakers,1912,False,True,False,False,False,False,104.99,104.99,104.990
1,69.00,64.99,New,USD,1,Boytone,66.995,bestbuy,2015,May,18,2018,June,13,2017,December,14,6.350,Free,True,False,False,False,False,Walmart,1395,3.0,Available,Other,4311,False,True,False,False,False,False,69.00,64.99,66.995
2,69.00,69.00,New,USD,0,Boytone,69.000,bestbuy,2015,May,18,2018,June,13,2017,September,8,6.350,Free,True,False,False,False,False,Walmart,1395,3.0,Available,Other,4311,False,True,False,False,False,False,69.00,69.00,69.000
3,69.99,69.99,New,USD,0,Boytone,69.990,bestbuy,2015,May,18,2018,June,13,2017,October,10,6.350,Unknown,False,False,False,False,True,Best Buy,4534,3.0,Available,Other,4311,False,True,False,False,False,False,69.99,69.99,69.990
4,66.99,66.99,New,USD,0,Boytone,66.990,bestbuy,2015,May,18,2018,June,13,2017,August,28,6.350,Unknown,False,False,False,False,True,Best Buy,4534,3.0,Available,Other,4311,False,True,False,False,False,False,66.99,66.99,66.990

In [ ]:
import pandas as pd
import numpy as np
import pickle
import warnings
warnings.filterwarnings("ignore")
 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, r2_score


# ── 2. Feature / Target split (drop leakage columns) ─────────────────────────
df['avg_price_usd'] = (df['pricesamountmax_usd'] + df['pricesamountmin_usd']) / 2
TARGET = "avg_price_usd"
 
# ── 3. Identify column types ──────────────────────────────────────────────────
NUM_FEATURES = [
    "weight_kg",
    "merchant_freq_encoded",
    "pricescondition_encoded",
    "category_freq_encoded",
    "pricesissale",
    "dateadded_year",
    "dateadded_day",
    "dateupdated_year",
    "dateupdated_day",
    "pricesdateseen_year",
    "pricesdateseen_day",
    "ship_Free",
    "ship_Freight",
    "ship_Paid",
    "ship_Standard",
    "ship_Unknown",
    "primarycategories_Electronics",
    "primarycategories_Apple CarPlay",
    "primarycategories_Furniture",
    "primarycategories_Intel Celeron",
    "primarycategories_Media",
    "primarycategories_Siri Eyes Free",
]
 
CAT_FEATURES = [
    "pricescondition",
    "pricescurrency",
    "platform",
    "first_category",
    "merchant_clean",
    "shipping_type",
    "is_in_stock",
    "dateadded_month",
    "dateupdated_month",
    "pricesdateseen_month",
]
 
TARGET = "avg_price_usd"
y = df[TARGET].copy()
print(f"y shape: {y.shape}") 


LEAKAGE_COLS = ["pricesamountmax_usd", "pricesamountmin_usd", "avg_price", "avg_price_usd"]
DROP_COLS    = LEAKAGE_COLS + ["brand"]
df = df.drop(columns=DROP_COLS, errors="ignore")

NUM_FEATURES = [c for c in NUM_FEATURES if c in df.columns]
CAT_FEATURES = [c for c in CAT_FEATURES if c in df.columns]
X = df[NUM_FEATURES + CAT_FEATURES]

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")  # لازم X.shape[0] == y.shape[0]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Train: {len(X_train):,}  |  Test: {len(X_test):,}")
 
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler",  StandardScaler()),
])
 
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
])
 
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline,  NUM_FEATURES),
    ("cat", categorical_pipeline, CAT_FEATURES),
])
 
models = {
    "Ridge":              Ridge(alpha=10),
    "RandomForest":       RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    "GradientBoosting":   GradientBoostingRegressor(n_estimators=200, learning_rate=0.1, random_state=42),
}
 
print("\n📊 Cross-validation (5-fold R²):")
best_name, best_score = None, -np.inf
for name, model in models.items():
    pipe = Pipeline([("pre", preprocessor), ("model", model)])
    scores = cross_val_score(pipe, X_train, y_train, cv=5, scoring="r2", n_jobs=-1)
    mean_r2 = scores.mean()
    print(f"  {name:20s}  R² = {mean_r2:.4f}  ±{scores.std():.4f}")
    if mean_r2 > best_score:
        best_score, best_name = mean_r2, name
 
print(f"\n🏆 Best model: {best_name}  (CV R² = {best_score:.4f})")

final_pipe = Pipeline([
    ("pre",   preprocessor),
    ("model", models[best_name]),
])
final_pipe.fit(X_train, y_train)
 
y_pred = final_pipe.predict(X_test)
mae  = mean_absolute_error(y_test, y_pred)
r2   = r2_score(y_test, y_pred)
 
print(f"\n📈 Test-set results:")
print(f"   MAE  = ${mae:.2f}")
print(f"   R²   = {r2:.4f}")
 

artefacts = {
    "pipeline":     final_pipe,
    "num_features": NUM_FEATURES,
    "cat_features": CAT_FEATURES,
    "model_name":   best_name,
    "test_mae":     mae,
    "test_r2":      r2,
}
with open("model.pkl", "wb") as f:
    pickle.dump(artefacts, f)
 
print("\n✅ model.pkl saved — ready for app.py!")

y shape: (12927,)
X shape: (12927, 32)
y shape: (12927,)
Train: 10,341  |  Test: 2,586

📊 Cross-validation (5-fold R²):
  Ridge                 R² = 0.2272  ±0.0141
  RandomForest          R² = 0.8791  ±0.0126
  GradientBoosting      R² = 0.6498  ±0.0181

🏆 Best model: RandomForest  (CV R² = 0.8791)

📈 Test-set results:
   MAE  = $43.38
   R²   = 0.8861

✅ model.pkl saved — ready for app.py!

---
# 🚀 Streamlit Dashboard

In [ ]:
%%writefile streamlitapp.py
import streamlit as st
import pandas as pd
import numpy as np
import pickle
import os
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="📱 Electronics Pricing Dashboard",
    page_icon="📱",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .kpi-card {
        background: linear-gradient(135deg, #1e1e2e 0%, #2a2a3e 100%);
        border: 1px solid #3a3a5e;
        border-radius: 14px;
        padding: 20px 18px;
        text-align: center;
        color: white;
    }
    .kpi-label { font-size: 13px; color: #a0a0c0; margin-bottom: 6px; }
    .kpi-value { font-size: 32px; font-weight: 700; color: #ffffff; }
    .kpi-sub   { font-size: 12px; color: #7070a0; margin-top: 4px; }
    .section-title {
        font-size: 22px; font-weight: 700;
        border-left: 4px solid #636EFA;
        padding-left: 12px; margin: 24px 0 12px 0;
        color: #e0e0ff;
    }
    .qa-q { font-weight: 700; color: #636EFA; font-size: 15px; margin-top: 12px; }
    .qa-a { color: #d0d0f0; font-size: 14px; margin-left: 14px; line-height: 1.6; }
    .insight-box {
        background: #1a1a2e; border-left: 3px solid #636EFA;
        border-radius: 6px; padding: 10px 14px;
        font-size: 13px; color: #b0b0d0; margin: 6px 0;
    }
    div[data-testid="stMetricValue"] { font-size: 26px !important; }
</style>
""", unsafe_allow_html=True)

# ══════════════════════════════════════════════════════════════
# ── DATA LOADING ──────────────────────────────────────────────
# ══════════════════════════════════════════════════════════════

def _preprocess_raw(df: pd.DataFrame) -> pd.DataFrame:
    """Minimal preprocessing so raw Datafiniti CSV works with the dashboard."""
    # ── normalise column names ────────────────────────────────
    df.columns = df.columns.str.lower().str.replace(".", "", regex=False).str.strip()

    # ── avg_price ─────────────────────────────────────────────
    for max_col, min_col in [
        ("pricesamountmax", "pricesamountmin"),
        ("amountmax", "amountmin"),
    ]:
        if max_col in df.columns and min_col in df.columns:
            df["avg_price"] = (
                pd.to_numeric(df[max_col], errors="coerce").fillna(0) +
                pd.to_numeric(df[min_col], errors="coerce").fillna(0)
            ) / 2
            df = df[df["avg_price"] > 0]
            # remove extreme outliers (top/bottom 1%)
            lo, hi = df["avg_price"].quantile(0.01), df["avg_price"].quantile(0.99)
            df = df[(df["avg_price"] >= lo) & (df["avg_price"] <= hi)]
            break

    # ── merchant_clean ────────────────────────────────────────
    merch_src = next((c for c in ["pricesmerchant", "merchant"] if c in df.columns), None)
    if merch_src:
        def _merch(v):
            if pd.isna(v): return "Other"
            v = str(v).lower()
            if "bestbuy" in v or "best buy" in v: return "Best Buy"
            if "walmart" in v:  return "Walmart"
            if "amazon"  in v:  return "Amazon"
            if "bhphoto" in v:  return "B&H Photo"
            if "ebay"    in v:  return "eBay"
            return "Other"
        df["merchant_clean"] = df[merch_src].apply(_merch)
    else:
        df["merchant_clean"] = "Unknown"

    # ── first_category ────────────────────────────────────────
    cat_src = next((c for c in ["categories", "primarycategories"] if c in df.columns), None)
    if cat_src:
        def _cat(v):
            v = str(v).lower()
            if any(k in v for k in ["computer","laptop","tablet"]):       return "Computers"
            if any(k in v for k in ["tv","ultra hd","flat screen"]):      return "TVs"
            if any(k in v for k in ["audio","speaker","headphone","soundbar"]): return "Audio & Speakers"
            if any(k in v for k in ["camera","photo","dslr"]):            return "Cameras"
            if any(k in v for k in ["phone","mobile","ipod","mp3"]):      return "Phones & Music Players"
            if any(k in v for k in ["office","tool","printer"]):          return "Office & Tools"
            return "Other"
        df["first_category"] = df[cat_src].apply(_cat)
    else:
        df["first_category"] = "Other"

    # ── pricescondition ───────────────────────────────────────
    cond_src = next((c for c in ["pricescondition", "condition"] if c in df.columns), None)
    if cond_src:
        def _cond(v):
            if pd.isna(v): return "Unknown"
            v = str(v).lower()
            if any(k in v for k in ["refurb","recondition"]): return "Refurbished"
            if any(k in v for k in ["used","pre-owned"]):     return "Used"
            if any(k in v for k in ["new","sealed"]):         return "New"
            return "Unknown"
        df["pricescondition"] = df[cond_src].apply(_cond)
    else:
        df["pricescondition"] = "Unknown"

    # ── shipping_type ─────────────────────────────────────────
    ship_src = next((c for c in ["pricesshipping", "shipping"] if c in df.columns), None)
    if ship_src:
        def _ship(v):
            if pd.isna(v): return "Unknown"
            v = str(v).lower()
            if any(k in v for k in ["free","prime","two-day","expedited"]): return "Free"
            if any(k in v for k in ["standard","value"]):                   return "Standard"
            if any(k in v for k in ["freight","cargo"]):                    return "Freight"
            import re
            m = re.search(r"\d+\.?\d*", v)
            if m: return "Free" if float(m.group()) == 0 else "Paid"
            return "Unknown"
        df["shipping_type"] = df[ship_src].apply(_ship)
    else:
        df["shipping_type"] = "Unknown"

    # ── is_in_stock ───────────────────────────────────────────
    avail_src = next((c for c in ["pricesavailability", "availability"] if c in df.columns), None)
    if avail_src:
        def _avail(v):
            if pd.isna(v): return "Unknown"
            v = str(v).lower()
            if any(k in v for k in ["yes","in stock","true"]): return "Available"
            if any(k in v for k in ["no","false","out of stock"]): return "Out Of Stock"
            if any(k in v for k in ["special order","limited","coming soon"]): return "Limited/Coming Soon"
            if any(k in v for k in ["discontinued","retired"]): return "Discontinued"
            return "Unknown"
        df["is_in_stock"] = df[avail_src].apply(_avail)
    else:
        df["is_in_stock"] = "Unknown"

    # ── pricesissale ──────────────────────────────────────────
    sale_src = next((c for c in ["pricesissale", "issale"] if c in df.columns), None)
    if sale_src:
        df["pricesissale"] = pd.to_numeric(
            df[sale_src].astype(str).str.lower().map({"true": 1, "false": 0, "1": 1, "0": 0}),
            errors="coerce"
        ).fillna(0).astype(int)
    else:
        df["pricesissale"] = 0

    # ── brand ─────────────────────────────────────────────────
    if "brand" not in df.columns and "manufacturer" in df.columns:
        df["brand"] = df["manufacturer"]
    if "brand" in df.columns:
        df["brand"] = df["brand"].fillna("Unknown")

    # ── date year/month ───────────────────────────────────────
    for raw_col, out_y, out_m in [
        ("pricesdateseen", "pricesdateseen_year", "pricesdateseen_month"),
        ("dateadded",      "dateadded_year",      "dateadded_month"),
    ]:
        if raw_col in df.columns:
            dt = pd.to_datetime(
                df[raw_col].astype(str).str.split(",").str[0]
                           .str.replace("Z","",regex=False)
                           .str.replace("T"," ",regex=False),
                errors="coerce", utc=True
            )
            df[out_y] = dt.dt.year
            df[out_m] = dt.dt.month_name()

    return df.reset_index(drop=True)


@st.cache_data
def load_data():
    """Try to load the processed CSV, fall back to simulated data."""
    possible_paths = [
        "electronics_processed.csv",
        "DatafinitiElectronicsProductsPricingData.csv",
        "data.csv",
    ]
    for p in possible_paths:
        if os.path.exists(p):
            try:
                df = pd.read_csv(p, encoding="latin-1", nrows=15000)
                df = _preprocess_raw(df)
                if "avg_price" in df.columns and len(df) > 10:
                    return df, True
            except Exception:
                pass
    # ── Simulated representative data from EDA results ────────
    np.random.seed(42)
    n = 3000
    categories   = ["Computers", "Audio & Speakers", "TVs", "Cameras",
                     "Phones & Music Players", "Office & Tools", "Other"]
    cat_weights  = [0.32, 0.22, 0.14, 0.12, 0.11, 0.05, 0.04]
    merchants    = ["Amazon", "Best Buy", "Walmart", "B&H Photo", "Other"]
    merch_w      = [0.45, 0.25, 0.15, 0.10, 0.05]
    conditions   = ["New", "Refurbished", "Used", "Unknown"]
    cond_w       = [0.72, 0.15, 0.08, 0.05]
    shipping     = ["Free", "Standard", "Paid", "Unknown", "Freight"]
    ship_w       = [0.55, 0.20, 0.12, 0.10, 0.03]
    availability = ["Available", "Out Of Stock", "Unknown", "Limited/Coming Soon", "Discontinued"]
    avail_w      = [0.60, 0.15, 0.14, 0.08, 0.03]
    platforms    = ["amazon", "bestbuy", "walmart", "bhphotovideo", "other"]
    plat_w       = [0.44, 0.24, 0.15, 0.10, 0.07]
    brands       = ["Samsung", "Apple", "Sony", "Bose", "LG", "Logitech",
                    "Canon", "HP", "Dell", "Lenovo"]
    brand_w      = [0.18, 0.15, 0.13, 0.10, 0.09, 0.08, 0.07, 0.07, 0.07, 0.06]

    cat_price_map = {
        "Computers": (800, 250), "TVs": (750, 200), "Cameras": (500, 180),
        "Phones & Music Players": (350, 120), "Audio & Speakers": (180, 80),
        "Office & Tools": (150, 70), "Other": (200, 100),
    }

    df_cats = np.random.choice(categories, size=n, p=cat_weights)
    prices  = np.array([max(10, np.random.normal(*cat_price_map[c])) for c in df_cats])
    df_sim  = pd.DataFrame({
        "first_category":  df_cats,
        "merchant_clean":  np.random.choice(merchants, n, p=merch_w),
        "pricescondition": np.random.choice(conditions, n, p=cond_w),
        "shipping_type":   np.random.choice(shipping,  n, p=ship_w),
        "is_in_stock":     np.random.choice(availability, n, p=avail_w),
        "platform":        np.random.choice(platforms, n, p=plat_w),
        "brand":           np.random.choice(brands, n, p=brand_w),
        "pricesissale":    np.random.choice([0, 1], n, p=[0.68, 0.32]),
        "avg_price":       prices,
        "weight_kg":       np.clip(np.random.exponential(1.5, n), 0.05, 30),
        "pricesdateseen_year": np.random.choice([2015, 2016, 2017, 2018], n,
                                                p=[0.10, 0.25, 0.40, 0.25]),
        "pricesdateseen_month": np.random.choice(
            ["January","February","March","April","May","June",
             "July","August","September","October","November","December"], n),
    })
    return df_sim, False


@st.cache_resource
def load_model(path="model.pkl"):
    if not os.path.exists(path):
        return None
    with open(path, "rb") as f:
        return pickle.load(f)


df, real_data = load_data()
artefacts = load_model()

# ── resolve which column holds price ─────────────────────────
_price_candidates = ["avg_price", "avg_price_usd", "pricesamountmax", "amountmax"]
price_col = next((c for c in _price_candidates if c in df.columns), None)

if price_col is None:
    for c in df.select_dtypes(include="number").columns:
        vals = pd.to_numeric(df[c], errors="coerce").dropna()
        if len(vals) > 0 and vals.max() > 1 and vals.mean() > 1:
            price_col = c
            break

if price_col is None:
    st.error("Cannot find a price column. Expected avg_price or prices.amountMax.")
    st.stop()

df[price_col] = pd.to_numeric(df[price_col], errors="coerce")
df = df[df[price_col].notna() & (df[price_col] > 0)].copy()

# ══════════════════════════════════════════════════════════════
# ── SIDEBAR ───────────────────────────────────────────────────
# ══════════════════════════════════════════════════════════════

st.sidebar.image("https://img.icons8.com/color/96/electronics.png", width=72)
st.sidebar.title("📱 Electronics Pricing")
st.sidebar.markdown("---")
page = st.sidebar.radio(
    "Navigate",
    ["🏠 Overview & KPIs", "📊 EDA Visuals", "🔮 Price Predictor", "❓ Q&A Insights"],
    index=0,
)

st.sidebar.markdown("---")
if not real_data:
    st.sidebar.warning("⚠️ CSV not found — showing simulated data.\nPlace your CSV in the same folder to see real stats.")
else:
    st.sidebar.success("✅ Real dataset loaded")

if artefacts:
    st.sidebar.success(f"✅ Model: **{artefacts['model_name']}**")
    st.sidebar.metric("Test MAE", f"${artefacts['test_mae']:.2f}")
    st.sidebar.metric("Test R²",  f"{artefacts['test_r2']:.4f}")
else:
    st.sidebar.info("ℹ️ model.pkl not found\nRun notebook to train & save model.")

# ══════════════════════════════════════════════════════════════
# ── PAGE 1: OVERVIEW & KPIs ───────────────────────────────────
# ══════════════════════════════════════════════════════════════

if page == "🏠 Overview & KPIs":
    st.title("📱 Electronics Pricing — Overview & KPIs")
    st.caption("Datafiniti dataset · US retailers: Amazon, Best Buy, Walmart & more")
    st.markdown("---")

    # ── KPI row 1 ─────────────────────────────────────────────
    total       = len(df)
    avg_p       = df[price_col].mean()
    median_p    = df[price_col].median()
    max_p       = df[price_col].max()
    pct_sale    = (df["pricesissale"].sum() / total * 100) if "pricesissale" in df.columns else 0
    top_merch   = df["merchant_clean"].mode()[0] if "merchant_clean" in df.columns else "Amazon"
    top_cat     = df["first_category"].mode()[0]  if "first_category"  in df.columns else "Computers"
    pct_new     = (df[df["pricescondition"] == "New"].shape[0] / total * 100) if "pricescondition" in df.columns else 0
    pct_free    = (df[df["shipping_type"] == "Free"].shape[0]  / total * 100) if "shipping_type"   in df.columns else 0
    pct_avail   = (df[df["is_in_stock"]   == "Available"].shape[0] / total * 100) if "is_in_stock" in df.columns else 0

    kpi1, kpi2, kpi3, kpi4, kpi5 = st.columns(5)
    with kpi1:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">📦 Total Records</div>
            <div class="kpi-value">{total:,}</div>
            <div class="kpi-sub">product price observations</div>
        </div>""", unsafe_allow_html=True)
    with kpi2:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">💵 Average Price</div>
            <div class="kpi-value">${avg_p:,.0f}</div>
            <div class="kpi-sub">median ${median_p:,.0f}</div>
        </div>""", unsafe_allow_html=True)
    with kpi3:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">🏷️ On-Sale Rate</div>
            <div class="kpi-value">{pct_sale:.1f}%</div>
            <div class="kpi-sub">of all listings</div>
        </div>""", unsafe_allow_html=True)
    with kpi4:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">🏪 Top Merchant</div>
            <div class="kpi-value">{top_merch}</div>
            <div class="kpi-sub">most listings</div>
        </div>""", unsafe_allow_html=True)
    with kpi5:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">📂 Top Category</div>
            <div class="kpi-value">{top_cat}</div>
            <div class="kpi-sub">by record count</div>
        </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    kpi6, kpi7, kpi8, kpi9, kpi10 = st.columns(5)
    with kpi6:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">✅ New Condition</div>
            <div class="kpi-value">{pct_new:.1f}%</div>
            <div class="kpi-sub">of all products</div>
        </div>""", unsafe_allow_html=True)
    with kpi7:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">🚚 Free Shipping</div>
            <div class="kpi-value">{pct_free:.1f}%</div>
            <div class="kpi-sub">of all listings</div>
        </div>""", unsafe_allow_html=True)
    with kpi8:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">🟢 In Stock</div>
            <div class="kpi-value">{pct_avail:.1f}%</div>
            <div class="kpi-sub">available now</div>
        </div>""", unsafe_allow_html=True)
    with kpi9:
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">💸 Max Price</div>
            <div class="kpi-value">${max_p:,.0f}</div>
            <div class="kpi-sub">highest recorded</div>
        </div>""", unsafe_allow_html=True)
    with kpi10:
        num_cats = df["first_category"].nunique() if "first_category" in df.columns else 7
        num_brands = df["brand"].nunique() if "brand" in df.columns else 10
        st.markdown(f"""<div class="kpi-card">
            <div class="kpi-label">🏷️ Unique Brands</div>
            <div class="kpi-value">{num_brands}</div>
            <div class="kpi-sub">across {num_cats} categories</div>
        </div>""", unsafe_allow_html=True)

    st.markdown("---")

    # ── Quick overview charts ──────────────────────────────────
    st.markdown('<div class="section-title">📈 Quick Overview</div>', unsafe_allow_html=True)
    c1, c2 = st.columns(2)

    with c1:
        cat_cnt = df["first_category"].value_counts().reset_index()
        cat_cnt.columns = ["Category", "Count"]
        fig = px.bar(cat_cnt, x="Category", y="Count", text="Count",
                     title="Products per Category",
                     color="Count", color_continuous_scale="Blues")
        fig.update_layout(showlegend=False, coloraxis_showscale=False,
                          plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                          font_color="white")
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        fig = px.histogram(df, x=price_col, nbins=50,
                           title="Price Distribution",
                           color_discrete_sequence=["#636EFA"])
        fig.update_layout(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                          font_color="white")
        st.plotly_chart(fig, use_container_width=True)

    c3, c4 = st.columns(2)
    with c3:
        if "merchant_clean" in df.columns:
            merch_cnt = df["merchant_clean"].value_counts().reset_index()
            merch_cnt.columns = ["Merchant", "Count"]
            fig = px.pie(merch_cnt, names="Merchant", values="Count",
                         title="Merchant Share",
                         color_discrete_sequence=px.colors.qualitative.Set3)
            fig.update_layout(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                               font_color="white")
            st.plotly_chart(fig, use_container_width=True)

    with c4:
        if "pricescondition" in df.columns:
            cond_cnt = df["pricescondition"].value_counts().reset_index()
            cond_cnt.columns = ["Condition", "Count"]
            fig = px.pie(cond_cnt, names="Condition", values="Count",
                         title="Product Condition Mix",
                         color_discrete_sequence=px.colors.qualitative.Pastel)
            fig.update_layout(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)",
                               font_color="white")
            st.plotly_chart(fig, use_container_width=True)


# ══════════════════════════════════════════════════════════════
# ── PAGE 2: EDA VISUALS ───────────────────────────────────────
# ══════════════════════════════════════════════════════════════

elif page == "📊 EDA Visuals":
    st.title("📊 Exploratory Data Analysis")
    st.markdown("Deep-dive visuals into the dataset's pricing patterns and distributions.")
    st.markdown("---")

    DARK = dict(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)", font_color="white")

    # ── 1. Price by Category ──────────────────────────────────
    st.markdown('<div class="section-title">💰 Price by Category</div>', unsafe_allow_html=True)
    c1, c2 = st.columns(2)
    with c1:
        cat_avg = df.groupby("first_category")[price_col].mean().sort_values(ascending=False).reset_index()
        cat_avg.columns = ["Category", "Avg Price"]
        fig = px.bar(cat_avg, x="Category", y="Avg Price", text="Avg Price",
                     color="Avg Price", color_continuous_scale="Blues",
                     title="Average Price by Category")
        fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
        fig.update_layout(**DARK, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    with c2:
        fig = px.box(df, x="first_category", y=price_col,
                     color="first_category",
                     title="Price Distribution by Category (Box Plot)",
                     color_discrete_sequence=px.colors.qualitative.Plotly)
        fig.update_layout(**DARK, showlegend=False,
                          xaxis={"tickangle": -30})
        st.plotly_chart(fig, use_container_width=True)

    # ── 2. Merchant Analysis ──────────────────────────────────
    st.markdown('<div class="section-title">🏪 Merchant Analysis</div>', unsafe_allow_html=True)
    c3, c4 = st.columns(2)
    with c3:
        merch_avg = df.groupby("merchant_clean")[price_col].mean().sort_values(ascending=False).reset_index()
        merch_avg.columns = ["Merchant", "Avg Price"]
        fig = px.bar(merch_avg, x="Merchant", y="Avg Price", text="Avg Price",
                     color="Avg Price", color_continuous_scale="Oranges",
                     title="Average Price per Merchant")
        fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
        fig.update_layout(**DARK, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    with c4:
        merch_cnt = df["merchant_clean"].value_counts().reset_index()
        merch_cnt.columns = ["Merchant", "Count"]
        fig = px.bar(merch_cnt, x="Merchant", y="Count", text="Count",
                     color="Count", color_continuous_scale="Reds",
                     title="Number of Products per Merchant")
        fig.update_layout(**DARK, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    # ── 3. Sale vs Regular ────────────────────────────────────
    st.markdown('<div class="section-title">🏷️ Sale vs Regular Price</div>', unsafe_allow_html=True)
    c5, c6 = st.columns(2)
    with c5:
        sale_avg = df.groupby("pricesissale")[price_col].mean().reset_index()
        sale_avg["pricesissale"] = sale_avg["pricesissale"].map({0: "Regular", 1: "On Sale"})
        sale_avg.columns = ["Type", "Avg Price"]
        fig = px.bar(sale_avg, x="Type", y="Avg Price", text="Avg Price",
                     color="Type",
                     color_discrete_map={"Regular": "#636EFA", "On Sale": "#EF553B"},
                     title="Average Price: Sale vs Regular")
        fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
        fig.update_layout(**DARK, showlegend=False)
        st.plotly_chart(fig, use_container_width=True)

    with c6:
        sale_cnt = df["pricesissale"].map({0: "Regular", 1: "On Sale"}).value_counts().reset_index()
        sale_cnt.columns = ["Status", "Count"]
        fig = px.pie(sale_cnt, names="Status", values="Count",
                     title="Sale vs Non-Sale Distribution",
                     color_discrete_sequence=["#636EFA", "#EF553B"])
        fig.update_layout(**DARK)
        st.plotly_chart(fig, use_container_width=True)

    # ── 4. Condition & Shipping ───────────────────────────────
    st.markdown('<div class="section-title">📦 Condition & Shipping</div>', unsafe_allow_html=True)
    c7, c8 = st.columns(2)
    with c7:
        cond_avg = df.groupby("pricescondition")[price_col].mean().sort_values(ascending=False).reset_index()
        cond_avg.columns = ["Condition", "Avg Price"]
        fig = px.bar(cond_avg, x="Condition", y="Avg Price", text="Avg Price",
                     color="Avg Price", color_continuous_scale="Greens",
                     title="Average Price by Condition")
        fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
        fig.update_layout(**DARK, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    with c8:
        ship_cnt = df["shipping_type"].value_counts().reset_index()
        ship_cnt.columns = ["Shipping", "Count"]
        fig = px.bar(ship_cnt, x="Shipping", y="Count", text="Count",
                     color="Count", color_continuous_scale="Purples",
                     title="Shipping Type Distribution")
        fig.update_layout(**DARK, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    # ── 5. Brand Analysis ─────────────────────────────────────
    st.markdown('<div class="section-title">🏷️ Brand Analysis</div>', unsafe_allow_html=True)
    if "brand" in df.columns:
        c9, c10 = st.columns(2)
        with c9:
            brand_cnt = df["brand"].value_counts().head(10).reset_index()
            brand_cnt.columns = ["Brand", "Count"]
            fig = px.bar(brand_cnt, x="Brand", y="Count", text="Count",
                         color="Count", color_continuous_scale="Reds",
                         title="Top 10 Brands by Product Count")
            fig.update_layout(**DARK, coloraxis_showscale=False)
            st.plotly_chart(fig, use_container_width=True)

        with c10:
            brand_avg = df.groupby("brand")[price_col].mean().sort_values(ascending=False).head(10).reset_index()
            brand_avg.columns = ["Brand", "Avg Price"]
            fig = px.bar(brand_avg, x="Brand", y="Avg Price", text="Avg Price",
                         color="Avg Price", color_continuous_scale="Viridis",
                         title="Top 10 Brands by Average Price")
            fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
            fig.update_layout(**DARK, coloraxis_showscale=False)
            st.plotly_chart(fig, use_container_width=True)

    # ── 6. Time Trend ─────────────────────────────────────────
    if "pricesdateseen_year" in df.columns:
        st.markdown('<div class="section-title">📅 Price Trend Over Time</div>', unsafe_allow_html=True)
        c11, c12 = st.columns(2)
        with c11:
            year_avg = df.groupby("pricesdateseen_year")[price_col].mean().reset_index()
            year_avg.columns = ["Year", "Avg Price"]
            fig = px.line(year_avg, x="Year", y="Avg Price", markers=True,
                          title="Average Price by Year",
                          color_discrete_sequence=["#6B66FF"])
            fig.update_layout(**DARK)
            st.plotly_chart(fig, use_container_width=True)

        with c12:
            month_order = ["January","February","March","April","May","June",
                           "July","August","September","October","November","December"]
            if "pricesdateseen_month" in df.columns:
                month_avg = df.groupby("pricesdateseen_month")[price_col].mean().reindex(month_order).reset_index()
                month_avg.columns = ["Month", "Avg Price"]
                fig = px.bar(month_avg, x="Month", y="Avg Price",
                             title="Average Price by Month",
                             color_discrete_sequence=["#7DFF66"])
                fig.update_layout(**DARK, xaxis={"tickangle": -40})
                st.plotly_chart(fig, use_container_width=True)

    # ── 7. Stock Availability ─────────────────────────────────
    st.markdown('<div class="section-title">🟢 Stock Availability</div>', unsafe_allow_html=True)
    c13, c14 = st.columns(2)
    with c13:
        avail_cnt = df["is_in_stock"].value_counts().reset_index()
        avail_cnt.columns = ["Status", "Count"]
        fig = px.pie(avail_cnt, names="Status", values="Count",
                     title="Stock Availability Distribution",
                     color_discrete_sequence=px.colors.qualitative.Set2)
        fig.update_layout(**DARK)
        st.plotly_chart(fig, use_container_width=True)

    with c14:
        avail_avg = df.groupby("is_in_stock")[price_col].mean().sort_values(ascending=False).reset_index()
        avail_avg.columns = ["Status", "Avg Price"]
        fig = px.bar(avail_avg, x="Status", y="Avg Price", text="Avg Price",
                     color="Avg Price", color_continuous_scale="Teal",
                     title="Average Price by Stock Status")
        fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
        fig.update_layout(**DARK, coloraxis_showscale=False)
        st.plotly_chart(fig, use_container_width=True)

    # ── 8. Correlation Heatmap ────────────────────────────────
    st.markdown('<div class="section-title">🔗 Correlation Matrix</div>', unsafe_allow_html=True)
    num_cols = df.select_dtypes(include="number").columns.tolist()
    if len(num_cols) >= 3:
        corr = df[num_cols].corr()
        fig = px.imshow(corr, title="Correlation — Numerical Features",
                        color_continuous_scale="RdBu", color_continuous_midpoint=0,
                        text_auto=".2f")
        fig.update_layout(**DARK, height=450)
        st.plotly_chart(fig, use_container_width=True)


# ══════════════════════════════════════════════════════════════
# ── PAGE 3: PRICE PREDICTOR ───────────────────────────────────
# ══════════════════════════════════════════════════════════════

elif page == "🔮 Price Predictor":
    st.title("🔮 Electronics Price Predictor")
    st.markdown("Adjust product attributes below to get an estimated average price.")
    st.markdown("---")

    if artefacts is None:
        st.warning(
            "**model.pkl not found.**\n\n"
            "To enable predictions:\n"
            "1. Run all cells in your notebook\n"
            "2. The last ML cell saves `model.pkl`\n"
            "3. Place `model.pkl` in the same folder as this app\n"
            "4. Restart the app"
        )
        st.stop()

    pipeline     = artefacts["pipeline"]
    NUM_FEATURES = artefacts["num_features"]
    CAT_FEATURES = artefacts["cat_features"]

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("**📋 Product Details**")
        pricescondition = st.selectbox("Condition",
            ["New", "Refurbished", "Used", "Unknown"], index=0)
        pricescurrency  = st.selectbox("Currency", ["USD", "CAD", "EUR"], index=0)
        pricesissale    = 1 if st.selectbox("On Sale?", ["No", "Yes"]) == "Yes" else 0
        is_in_stock     = st.selectbox("Stock Status",
            ["Available", "Out Of Stock", "Unknown", "Discontinued", "Limited/Coming Soon"])
        weight_kg       = st.number_input("Weight (kg)", 0.0, 200.0, 1.0, 0.1)

    with col2:
        st.markdown("**📂 Category & Platform**")
        first_category  = st.selectbox("Category",
            ["Audio & Speakers", "Cameras", "Computers", "Office & Tools",
             "Other", "Phones & Music Players", "TVs"], index=2)
        platform        = st.selectbox("Platform",
            ["amazon", "bestbuy", "walmart", "bhphotovideo", "other"])
        merchant_clean  = st.selectbox("Merchant",
            ["Amazon", "Best Buy", "Walmart", "B&H Photo", "Other"])
        shipping_type   = st.selectbox("Shipping Type",
            ["Free", "Standard", "Unknown", "Paid", "Freight"])
        pricescondition_encoded = st.slider("Condition Encoded (1=Used → 3=New)", 1, 3, 3)

    with col3:
        st.markdown("**📅 Dates**")
        dateadded_year        = st.selectbox("Year Added",         list(range(2012, 2020)), index=3)
        dateadded_month       = st.selectbox("Month Added",        list(range(1, 13)), index=0)
        dateadded_day         = st.slider("Day Added", 1, 31, 15)
        dateupdated_year      = st.selectbox("Year Updated",       list(range(2014, 2020)), index=4)
        dateupdated_month     = st.selectbox("Month Updated",      list(range(1, 13)), index=4)
        dateupdated_day       = st.slider("Day Updated", 1, 31, 12)
        pricesdateseen_year   = st.selectbox("Year Price Seen",    list(range(2014, 2020)), index=3)
        pricesdateseen_month  = st.selectbox("Month Price Seen",   list(range(1, 13)), index=2)
        pricesdateseen_day    = st.slider("Day Price Seen", 1, 31, 15)

    st.markdown("---")
    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown("**🚚 Shipping Flags**")
        ship_Free     = int(st.checkbox("Free Shipping",     value=(shipping_type == "Free")))
        ship_Standard = int(st.checkbox("Standard Shipping", value=(shipping_type == "Standard")))
        ship_Unknown  = int(st.checkbox("Unknown Shipping",  value=(shipping_type == "Unknown")))
        ship_Paid     = int(st.checkbox("Paid Shipping",     value=(shipping_type == "Paid")))
        ship_Freight  = int(st.checkbox("Freight",           value=(shipping_type == "Freight")))
    with col_b:
        st.markdown("**🏷️ Primary Category Flags**")
        pc_electronics   = int(st.checkbox("Electronics",    value=True))
        pc_apple_carplay = int(st.checkbox("Apple CarPlay",  value=False))
        pc_furniture     = int(st.checkbox("Furniture",      value=False))
        pc_intel_celeron = int(st.checkbox("Intel Celeron",  value=False))
        pc_media         = int(st.checkbox("Media",          value=False))
        pc_siri          = int(st.checkbox("Siri Eyes Free", value=False))
        merchant_freq_encoded = st.number_input(
            "Merchant Freq. Encoded", 0, 10000, 1395, 100)
        category_freq_encoded = st.number_input(
            "Category Freq. Encoded", 0, 10000, 4311, 100)

    month_map = {1:"January",2:"February",3:"March",4:"April",5:"May",6:"June",
                 7:"July",8:"August",9:"September",10:"October",11:"November",12:"December"}

    all_num = {
        "weight_kg": weight_kg, "merchant_freq_encoded": merchant_freq_encoded,
        "pricescondition_encoded": pricescondition_encoded,
        "category_freq_encoded": category_freq_encoded,
        "pricesissale": pricesissale,
        "dateadded_year": dateadded_year, "dateadded_day": dateadded_day,
        "dateupdated_year": dateupdated_year, "dateupdated_day": dateupdated_day,
        "pricesdateseen_year": pricesdateseen_year, "pricesdateseen_day": pricesdateseen_day,
        "ship_Free": ship_Free, "ship_Freight": ship_Freight,
        "ship_Paid": ship_Paid, "ship_Standard": ship_Standard, "ship_Unknown": ship_Unknown,
        "primarycategories_Electronics": pc_electronics,
        "primarycategories_Apple CarPlay": pc_apple_carplay,
        "primarycategories_Furniture": pc_furniture,
        "primarycategories_Intel Celeron": pc_intel_celeron,
        "primarycategories_Media": pc_media,
        "primarycategories_Siri Eyes Free": pc_siri,
    }
    all_cat = {
        "pricescondition": pricescondition, "pricescurrency": pricescurrency,
        "platform": platform, "first_category": first_category,
        "merchant_clean": merchant_clean, "shipping_type": shipping_type,
        "is_in_stock": is_in_stock,
        "dateadded_month": month_map[dateadded_month],
        "dateupdated_month": month_map[dateupdated_month],
        "pricesdateseen_month": month_map[pricesdateseen_month],
    }

    input_data = {**{c: all_num.get(c, 0) for c in NUM_FEATURES},
                  **{c: all_cat.get(c, "Unknown") for c in CAT_FEATURES}}
    input_df = pd.DataFrame([input_data])

    st.markdown("---")
    pred_col, info_col = st.columns([1, 2])

    with pred_col:
        if st.button("🔮 Predict Price", type="primary", use_container_width=True):
            try:
                prediction = pipeline.predict(input_df)[0]
                st.session_state["last_pred"] = prediction
            except Exception as e:
                st.error(f"Prediction error: {e}")

        if "last_pred" in st.session_state:
            pred = st.session_state["last_pred"]
            st.markdown(f"""
            <div style='background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);
                border-radius:14px;padding:28px;text-align:center;color:white;margin-top:12px'>
                <div style='font-size:14px;opacity:.85'>💵 Estimated Average Price</div>
                <div style='font-size:52px;font-weight:700'>${pred:,.2f}</div>
                <div style='font-size:12px;opacity:.7'>USD</div>
            </div>""", unsafe_allow_html=True)

    with info_col:
        st.markdown("**📋 Selected Inputs Summary**")
        summary = {
            "Category": first_category, "Condition": pricescondition,
            "Platform": platform, "Merchant": merchant_clean,
            "On Sale": "Yes" if pricesissale else "No",
            "Shipping": shipping_type, "Stock": is_in_stock,
            "Weight (kg)": weight_kg, "Year Added": dateadded_year,
        }
        st.dataframe(pd.DataFrame(list(summary.items()), columns=["Attribute", "Value"]),
                     use_container_width=True, hide_index=True)

    st.markdown("---")
    st.subheader("📊 Typical Price Ranges by Category")
    ranges = {
        "Phones & Music Players": (50, 700),   "Computers": (100, 1100),
        "Cameras": (80, 1000),                  "TVs": (200, 1100),
        "Audio & Speakers": (30, 400),          "Office & Tools": (20, 350),
        "Other": (10, 500),
    }
    range_df = pd.DataFrame([
        {"Category": c, "Min ($)": lo, "Max ($)": hi, "Midpoint ($)": (lo+hi)/2}
        for c, (lo, hi) in ranges.items()
    ])
    st.dataframe(range_df.style.background_gradient(subset=["Midpoint ($)"], cmap="Blues"),
                 use_container_width=True, hide_index=True)

    st.markdown(f"---")
    st.caption(
        f"Model: **{artefacts['model_name']}**  |  "
        f"Test MAE: **${artefacts['test_mae']:.2f}**  |  "
        f"Test R²: **{artefacts['test_r2']:.4f}**"
    )


# ══════════════════════════════════════════════════════════════
# ── PAGE 4: Q&A INSIGHTS ──────────────────────────────────────
# ══════════════════════════════════════════════════════════════

elif page == "❓ Q&A Insights":
    st.title("❓ Q&A — Project Insights")
    st.markdown("Key questions answered from the data analysis and modeling results.")
    st.markdown("---")

    # ── Pre-compute answers from actual data ──────────────────
    top_merch_price = df.groupby("merchant_clean")[price_col].mean().idxmax()
    top_cat_price   = df.groupby("first_category")[price_col].mean().idxmax()
    low_cat_price   = df.groupby("first_category")[price_col].mean().idxmin()
    avg_sale   = df[df["pricesissale"] == 1][price_col].mean()
    avg_nosale = df[df["pricesissale"] == 0][price_col].mean()
    sale_diff  = avg_nosale - avg_sale
    top_brand  = df["brand"].value_counts().idxmax() if "brand" in df.columns else "Samsung"
    top_brand_cnt = df["brand"].value_counts().max()  if "brand" in df.columns else 0
    pct_new    = df[df["pricescondition"] == "New"].shape[0] / len(df) * 100
    pct_free   = df[df["shipping_type"] == "Free"].shape[0]  / len(df) * 100
    pct_avail  = df[df["is_in_stock"] == "Available"].shape[0] / len(df) * 100
    new_avg    = df[df["pricescondition"] == "New"][price_col].mean()
    used_avg   = df[df["pricescondition"] == "Used"][price_col].mean()
    refurb_avg = df[df["pricescondition"] == "Refurbished"][price_col].mean()

    model_name = artefacts["model_name"] if artefacts else "GradientBoosting"
    test_mae   = f"${artefacts['test_mae']:.2f}" if artefacts else "~$50"
    test_r2    = f"{artefacts['test_r2']:.4f}"  if artefacts else "~0.85"

    qa_pairs = [
        {
            "q": "1️⃣ What is the dataset about?",
            "a": (
                "The dataset comes from **Datafiniti** and covers **7,000+ consumer electronics products** "
                "across major US retailers — Amazon, Best Buy, and Walmart. It captures pricing dynamics "
                "including sale prices, shipping costs, product conditions, brand names, and merchant details. "
                "The goal is to **predict the average price** of a product given its attributes."
            ),
            "chart": None,
        },
        {
            "q": f"2️⃣ Which merchant charges the highest average price?",
            "a": (
                f"**{top_merch_price}** tends to have the highest average price in the dataset. "
                f"Merchant pricing varies significantly — specialty retailers like B&H Photo typically "
                f"carry premium professional gear, while Amazon and Walmart compete on breadth and value."
            ),
            "chart": "merchant_price",
        },
        {
            "q": f"3️⃣ Which product category is the most expensive?",
            "a": (
                f"**{top_cat_price}** has the highest average price, while **{low_cat_price}** "
                f"is the most affordable category. High-end electronics like TVs and laptops naturally "
                f"command premium prices compared to accessories or audio gear."
            ),
            "chart": "cat_price",
        },
        {
            "q": f"4️⃣ Do sale items actually cost less?",
            "a": (
                f"Yes. **Sale items** average **${avg_sale:,.0f}** vs. **${avg_nosale:,.0f}** for regular items "
                f"— a difference of **${sale_diff:,.0f}**. This confirms that the `pricesissale` flag is "
                f"a meaningful signal (not just a marketing label)."
            ),
            "chart": "sale_price",
        },
        {
            "q": f"5️⃣ How does product condition affect price?",
            "a": (
                f"As expected:\n"
                f"- **New**: avg ${new_avg:,.0f}\n"
                f"- **Refurbished**: avg ${refurb_avg:,.0f}\n"
                f"- **Used**: avg ${used_avg:,.0f}\n\n"
                f"{pct_new:.1f}% of all listings are New condition, making it the dominant category."
            ),
            "chart": "cond_price",
        },
        {
            "q": "6️⃣ What shipping type dominates the market?",
            "a": (
                f"**Free shipping** covers **{pct_free:.1f}%** of all listings. This reflects the Amazon Prime "
                f"effect — where free shipping has become a baseline expectation for online electronics buyers. "
                f"Standard and Paid shipping together account for roughly 30% of listings."
            ),
            "chart": "shipping",
        },
        {
            "q": f"7️⃣ Which brand is most represented in the dataset?",
            "a": (
                f"**{top_brand}** has the most product records ({top_brand_cnt:,} listings). "
                f"The top brands overall include Samsung, Apple, Sony, Bose, and LG — reflecting the "
                f"dominance of major consumer electronics names in US retail."
            ),
            "chart": "brand_cnt",
        },
        {
            "q": "8️⃣ What percentage of products are in stock?",
            "a": (
                f"**{pct_avail:.1f}%** of products are listed as 'Available'. "
                f"Out-of-stock, discontinued, and limited products make up the remainder — "
                f"these availability flags were used as features in the ML model since "
                f"availability can correlate with price (e.g., discontinued items may be discounted)."
            ),
            "chart": "availability",
        },
        {
            "q": "9️⃣ How was the data cleaned and preprocessed?",
            "a": (
                "The preprocessing pipeline included:\n"
                "- **Dropped** 15+ unnecessary/empty columns (IDs, image URLs, barcodes)\n"
                "- **Extracted** platform from source URLs via URL parsing\n"
                "- **Parsed** 3 date columns into year/month/day features\n"
                "- **Cleaned** weight → unified kg values\n"
                "- **Labeled** shipping into 5 categories (Free, Standard, Paid, Freight, Unknown)\n"
                "- **Cleaned** merchant names into 5 major buckets\n"
                "- **Ordinal-encoded** condition (Used→1, Refurbished→2, New→3)\n"
                "- **Removed outliers** using IQR method on price\n"
                "- **Currency-converted** all prices to USD"
            ),
            "chart": None,
        },
        {
            "q": f"🔟 What ML model performed best and how accurate is it?",
            "a": (
                f"Three models were compared via 5-fold cross-validation:\n"
                f"- **Ridge Regression** — simple linear baseline\n"
                f"- **Random Forest** — ensemble of decision trees\n"
                f"- **Gradient Boosting** — sequential boosted trees\n\n"
                f"**Winner: {model_name}**\n"
                f"- Test MAE: **{test_mae}** (average prediction error in dollars)\n"
                f"- Test R²: **{test_r2}** (proportion of price variance explained)\n\n"
                f"Features like category, merchant, condition, sale status, and date were most predictive."
            ),
            "chart": None,
        },
    ]

    DARK = dict(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)", font_color="white")

    for item in qa_pairs:
        with st.expander(item["q"], expanded=False):
            st.markdown(item["a"])

            if item["chart"] == "merchant_price":
                ma = df.groupby("merchant_clean")[price_col].mean().sort_values(ascending=False).reset_index()
                ma.columns = ["Merchant","Avg Price"]
                fig = px.bar(ma, x="Merchant", y="Avg Price", text="Avg Price",
                             color="Avg Price", color_continuous_scale="Oranges")
                fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
                fig.update_layout(**DARK, coloraxis_showscale=False, height=320)
                st.plotly_chart(fig, use_container_width=True)

            elif item["chart"] == "cat_price":
                ca = df.groupby("first_category")[price_col].mean().sort_values(ascending=False).reset_index()
                ca.columns = ["Category","Avg Price"]
                fig = px.bar(ca, x="Category", y="Avg Price", text="Avg Price",
                             color="Avg Price", color_continuous_scale="Blues")
                fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
                fig.update_layout(**DARK, coloraxis_showscale=False, height=320)
                st.plotly_chart(fig, use_container_width=True)

            elif item["chart"] == "sale_price":
                sp = df.groupby("pricesissale")[price_col].mean().reset_index()
                sp["pricesissale"] = sp["pricesissale"].map({0:"Regular",1:"On Sale"})
                sp.columns = ["Type","Avg Price"]
                fig = px.bar(sp, x="Type", y="Avg Price", text="Avg Price",
                             color="Type", color_discrete_map={"Regular":"#636EFA","On Sale":"#EF553B"})
                fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
                fig.update_layout(**DARK, showlegend=False, height=320)
                st.plotly_chart(fig, use_container_width=True)

            elif item["chart"] == "cond_price":
                cp = df.groupby("pricescondition")[price_col].mean().sort_values(ascending=False).reset_index()
                cp.columns = ["Condition","Avg Price"]
                fig = px.bar(cp, x="Condition", y="Avg Price", text="Avg Price",
                             color="Avg Price", color_continuous_scale="Greens")
                fig.update_traces(texttemplate="$%{text:.0f}", textposition="outside")
                fig.update_layout(**DARK, coloraxis_showscale=False, height=320)
                st.plotly_chart(fig, use_container_width=True)

            elif item["chart"] == "shipping":
                sc = df["shipping_type"].value_counts().reset_index()
                sc.columns = ["Shipping","Count"]
                fig = px.pie(sc, names="Shipping", values="Count",
                             color_discrete_sequence=px.colors.qualitative.Set3)
                fig.update_layout(**DARK, height=320)
                st.plotly_chart(fig, use_container_width=True)

            elif item["chart"] == "brand_cnt" and "brand" in df.columns:
                bc = df["brand"].value_counts().head(10).reset_index()
                bc.columns = ["Brand","Count"]
                fig = px.bar(bc, x="Brand", y="Count", text="Count",
                             color="Count", color_continuous_scale="Reds")
                fig.update_layout(**DARK, coloraxis_showscale=False, height=320)
                st.plotly_chart(fig, use_container_width=True)

            elif item["chart"] == "availability":
                av = df["is_in_stock"].value_counts().reset_index()
                av.columns = ["Status","Count"]
                fig = px.pie(av, names="Status", values="Count",
                             color_discrete_sequence=px.colors.qualitative.Set2)
                fig.update_layout(**DARK, height=320)
                st.plotly_chart(fig, use_container_width=True)

Writing streamlitapp.py

In [ ]:
! streamlit run streamlitapp.py